export interface TourStepItem {
  targetId: string;
  title: string;
  description: string;
  actionGesture: string; // e.g. "👆 Chạm 1 lần", "↔️ Vuốt ngang", "📸 Quét Camera", "📡 Chạm NFC"
  touchPoint: string; // Vị trí điểm chạm cụ thể trên màn hình
  instruction: string; // Hướng dẫn thao tác
  systemResponse: string; // Phản hồi từ hệ thống
  roleNote?: string; // Ghi chú phân quyền (Ban Truyền Thông, Quản Trị, Hội viên)
  proTip?: string; // Mẹo doanh nhân
  icon?: string;
  position?: "top" | "bottom" | "auto";
}

export interface ScreenGuideItem {
  id: string;
  title: string;
  subtitle: string;
  route: string;
  badge: string;
  iconName: string;
  category: "core" | "card-ai" | "trade" | "events" | "network";
  themeColor: string;
  screenSummary: string;
  mockupMockTitle: string;
  mockupElements: {
    id: string;
    stepIndex: number;
    label: string;
    x: number; // percentage left 0-100
    y: number; // percentage top 0-100
    badgePosition: "top" | "bottom" | "left" | "right";
  }[];
  steps: TourStepItem[];
}

export const APP_SCREEN_TOURS: ScreenGuideItem[] = [
  {
    id: "association-home",
    title: "Màn hình Trang Chủ",
    subtitle: "Dashboard điều hành & Thẻ hội viên VIP Gold",
    route: "/association",
    badge: "Màn 1/10",
    iconName: "Home",
    category: "core",
    themeColor: "#003B95",
    screenSummary: "Không gian số trung tâm của CLB Doanh Nhân CEO 1983. Hiển thị thẻ hội viên VIP, số điện thoại, danh thiếp và các lối tắt kết nối giao thương nhanh.",
    mockupMockTitle: "Trang Chủ CEO 1983",
    mockupElements: [
      { id: "tour-member-card", stepIndex: 1, label: "Thẻ Hội Viên VIP Gold", x: 50, y: 22, badgePosition: "bottom" },
      { id: "tour-quick-edit-btn", stepIndex: 2, label: "Nút Sửa Hồ Sơ Nhanh", x: 88, y: 35, badgePosition: "left" },
      { id: "tour-quick-actions", stepIndex: 3, label: "Tiện Ích 1-Chạm", x: 50, y: 55, badgePosition: "top" },
      { id: "tour-opportunities-stats", stepIndex: 4, label: "Chỉ Số Giao Thương", x: 50, y: 78, badgePosition: "top" },
    ],
    steps: [
      {
        targetId: "tour-member-card",
        title: "Thẻ Hội Viên VIP Gold & Nhận Diện Số",
        actionGesture: "👆 Chạm 1 lần vào thẻ",
        touchPoint: "Mặt thẻ hội viên ở trung tâm nửa trên màn hình",
        instruction: "Chạm trực tiếp vào thẻ để mở mã QR phóng to. Đại biểu xuất trình mã này khi tới quầy lễ tân đại hội.",
        systemResponse: "Mở Modal Thẻ Thành Viên với mã QR động, tên công ty và số điện thoại liên hệ.",
        proTip: "Thẻ tích hợp mã định danh M1983 cá nhân hóa, đồng bộ thời gian thực với dữ liệu CRM CLB.",
        icon: "🎖️",
        description: "Thẻ nhận diện số chính thức của Quý Hội viên trong Hiệp hội CEO 1983. Hiển thị ảnh đại diện, ảnh bìa, mã hội viên và doanh nghiệp.",
      },
      {
        targetId: "tour-quick-edit-btn",
        title: "Chỉnh Sửa Hồ Sơ Doanh Nhân Nhanh",
        actionGesture: "👆 Chạm icon cây bút chì",
        touchPoint: "Góc dưới bên phải thẻ hội viên (hoặc nút Đổi ảnh bìa ở góc trên)",
        instruction: "Bấm icon bút chì để cập nhật ảnh đại diện, chức vụ hoặc tên thương hiệu doanh nghiệp trong 3 giây.",
        systemResponse: "Mở Bottom Sheet Chỉnh sửa nhanh, lưu trực tiếp vào bộ nhớ máy và đồng bộ lên hệ thống.",
        proTip: "Bạn có thể chụp ảnh trực tiếp từ camera điện thoại để làm ảnh bìa sang trọng cho thẻ của mình.",
        icon: "✏️",
        description: "Cập nhật nhanh thông tin cá nhân và thương hiệu doanh nghiệp mà không cần trải qua nhiều bước cài đặt phức tạp.",
      },
      {
        targetId: "tour-quick-actions",
        title: "Cụm Tiện Ích 1-Chạm Tốc Độ Cao",
        actionGesture: "👆 Chạm vào từng icon nghiệp vụ",
        touchPoint: "Thanh tiện ích 4 phím tắt: Vé Check-in, Biểu quyết, Lịch sử, Danh bạ",
        instruction: "Chạm icon 'Vé Check-in' để xuất trình vé, 'Biểu quyết' để bỏ phiếu, 'Danh bạ' để tìm đối tác.",
        systemResponse: "Điều hướng siêu tốc tới đúng phân hệ nghiệp vụ tương ứng.",
        roleNote: "Thành viên Ban Truyền Thông được cấp quyền sẽ thấy nút Quét vé sự kiện tại đây.",
        proTip: "Các chấm đỏ thông báo sẽ tự động biến mất khi bạn đã bấm vào xem tiện ích đó.",
        icon: "⚡",
        description: "Truy cập nhanh vào các tính năng thường dùng nhất trong các buổi sinh hoạt định kỳ và sự kiện thường niên.",
      },
      {
        targetId: "tour-opportunities-stats",
        title: "Bảng Chỉ Số Giao Thương Realtime",
        actionGesture: "👆 Chạm vào thẻ chỉ số để xem chi tiết",
        touchPoint: "Khối thống kê Cơ hội kinh doanh & Giá trị giao dịch ở giữa trang",
        instruction: "Chạm vào ô Cơ hội mở để xem các tin chào mua/chào bán mới nhất từ 200+ CEO trong khối.",
        systemResponse: "Chuyển sang Sàn Giao Thương B2B với bộ lọc ngành nghề tự động.",
        proTip: "Hàng tuần Ban Xúc Tiến Thương Mại sẽ tổng kết các giao dịch thành công tại khối này.",
        icon: "💼",
        description: "Theo dõi số lượng cơ hội kinh doanh đang mở và tổng giá trị giao thương nội khối đã được kích hoạt.",
      },
    ],
  },
  {
    id: "association-card",
    title: "Màn hình Thẻ Hội Viên & Danh Thiếp Số",
    subtitle: "Chạm thẻ thông minh NFC & Quét Card Visit AI",
    route: "/association/card",
    badge: "Màn 2/10",
    iconName: "CreditCard",
    category: "card-ai",
    themeColor: "#19194D",
    screenSummary: "Tấm danh thiếp số 5.0 chuẩn mực quốc tế của CEO 1983. Hỗ trợ chạm thẻ NFC vào lưng điện thoại đối tác, quét card visit giấy bằng AI và cài đặt quyền riêng tư.",
    mockupMockTitle: "Danh Thiếp Số CEO 1983",
    mockupElements: [
      { id: "tour-card-visit", stepIndex: 1, label: "Mặt Thẻ Danh Thiếp 3D", x: 50, y: 25, badgePosition: "bottom" },
      { id: "tour-card-qr-scan", stepIndex: 2, label: "Quét QR & Chụp AI", x: 50, y: 48, badgePosition: "bottom" },
      { id: "tour-card-nfc-action", stepIndex: 3, label: "Ghi Thẻ NFC Thông Minh", x: 50, y: 64, badgePosition: "top" },
      { id: "tour-card-edit-action", stepIndex: 4, label: "Quyền Riêng Tư & Chỉnh Sửa", x: 50, y: 82, badgePosition: "top" },
    ],
    steps: [
      {
        targetId: "tour-card-visit",
        title: "Mặt Thẻ Danh Thiếp Điện Tử Doanh Nhân",
        actionGesture: "👆 Chạm mã QR trên thẻ để phóng to",
        touchPoint: "Mặt thẻ điện tử hiển thị Họ tên, Chức vụ, Logo và Mã QR ở góc phải",
        instruction: "Đưa mã QR trên thẻ cho đối tác dùng camera iPhone hoặc Zalo quét để lưu danh bạ 1 giây.",
        systemResponse: "Mở trang hồ sơ công khai của bạn trên trình duyệt đối tác mà họ không cần cài app.",
        proTip: "Bấm vào logo công ty ở góc trên bên phải thẻ để cập nhật logo thương hiệu mới của bạn.",
        icon: "📇",
        description: "Danh thiếp số chuẩn mực thể hiện thương hiệu cá nhân và pháp nhân công ty với nhận diện Hiệp Hội CEO 1983.",
      },
      {
        targetId: "tour-card-qr-scan",
        title: "Quét QR & Chụp Danh Thiếp Bằng AI",
        actionGesture: "👆 Chạm nút 'Quét QR' hoặc 'Chụp danh thiếp'",
        touchPoint: "Cặp nút hành động chính nằm ngay dưới thẻ hội viên",
        instruction: "Bấm 'Chụp danh thiếp', hướng camera vào card visit giấy của đối tác để AI bóc tách thông tin tự động.",
        systemResponse: "AI Vision quét họ tên, SĐT, email, công ty và tự động lưu vào sổ danh bạ đối tác.",
        proTip: "Bạn cũng có thể chọn ảnh danh thiếp có sẵn trong thư viện ảnh điện thoại để AI nhận diện.",
        icon: "📸",
        description: "Công nghệ AI OCR nhận dạng quang học siêu tốc giúp bạn số hóa toàn bộ cọc danh thiếp giấy sau mỗi hội thảo.",
      },
      {
        targetId: "tour-card-nfc-action",
        title: "Chạm Ghi Thẻ Thông Minh NFC",
        actionGesture: "📡 Áp thẻ NFC vào lưng điện thoại",
        touchPoint: "Mục Ghi thẻ NFC kết nối không dây",
        instruction: "Bấm 'Ghi thẻ NFC', sau đó áp chiếc thẻ kim loại CEO 1983 vào mặt lưng điện thoại khoảng 2 giây.",
        systemResponse: "Hệ thống truyền link định danh số vào chip NFC. Khi chạm thẻ vào điện thoại ai, danh thiếp sẽ tự bật lên.",
        roleNote: "Hoạt động trực tiếp trên điện thoại có hỗ trợ Web NFC (Android Chrome và iOS Capacitor).",
        proTip: "Một chiếc thẻ NFC có thể ghi đè cập nhật lại thông tin hàng triệu lần miễn phí.",
        icon: "📡",
        description: "Giao tiếp trường gần NFC mang lại phong thái đỉnh cao cho doanh nhân khi đi giao thiệp và gặp gỡ đối tác lớn.",
      },
      {
        targetId: "tour-card-edit-action",
        title: "Cài Đặt Quyền Riêng Tư & Chia Sẻ",
        actionGesture: "👆 Chạm 'Chỉnh sửa' hoặc 'Chia sẻ'",
        touchPoint: "Hàng nút tiện ích: Chỉnh sửa, Chia sẻ, Sao chép link",
        instruction: "Bấm 'Chỉnh sửa' để chủ động bật/tắt hiển thị Số điện thoại, Email hoặc Zalo trên danh thiếp công khai.",
        systemResponse: "Mở bảng cấu hình bảo mật thông tin cá nhân riêng biệt.",
        proTip: "Bấm 'Sao chép' để lấy đường dẫn danh thiếp ngắn gọn gửi qua tin nhắn Zalo, SMS cho đối tác.",
        icon: "🔒",
        description: "Chủ động kiểm soát mức độ hiển thị thông tin nhạy cảm của lãnh đạo doanh nghiệp trước công chúng.",
      },
    ],
  },
  {
    id: "association-checkin",
    title: "Màn hình Vé Sự Kiện & Soát Vé QR",
    subtitle: "Check-in 1 giây tại cổng & Quyền Soát Vé Ban Truyền Thông",
    route: "/association/checkin",
    badge: "Màn 3/10",
    iconName: "QrCode",
    category: "events",
    themeColor: "#003B95",
    screenSummary: "Thẻ vé điện tử VIP tham dự Đại hội, Gala và Diễn đàn kinh tế. Kiểm tra chính xác số bàn tiệc VIP, số ghế, mã quay thưởng và máy quét dành riêng cho Ban Truyền Thông.",
    mockupMockTitle: "Vé Check-in Sự Kiện",
    mockupElements: [
      { id: "tour-checkin-ticket", stepIndex: 1, label: "Thẻ Vé Điện Tử VIP", x: 50, y: 22, badgePosition: "bottom" },
      { id: "tour-checkin-seat", stepIndex: 2, label: "Vị Trí Ghế & Bàn Tiệc VIP", x: 50, y: 46, badgePosition: "top" },
      { id: "tour-checkin-media-badge", stepIndex: 3, label: "Phân Quyền Ban Truyền Thông", x: 50, y: 64, badgePosition: "top" },
      { id: "tour-checkin-mode-toggle", stepIndex: 4, label: "Máy Quét Camera Check-in", x: 50, y: 84, badgePosition: "top" },
    ],
    steps: [
      {
        targetId: "tour-checkin-ticket",
        title: "Thẻ Vé Điện Tử VIP Standard Pass",
        actionGesture: "👁️ Xuất trình màn hình vé tại cổng",
        touchPoint: "Khung vé điện tử viền xanh Navy ở trung tâm màn hình",
        instruction: "Giữ màn hình sáng và đưa mã QR trên thẻ vé này cho Lễ tân hoặc Ban Truyền Thông quét tại cửa vào.",
        systemResponse: "Khi được quét, màn hình lập tức đóng dấu mộc xanh 'ĐÃ CHECK-IN THÀNH CÔNG' kèm hiệu ứng âm thanh.",
        proTip: "Vé hiển thị rõ mã vé cá nhân hóa (VD: TKT-EVT-M1983-001) và tên đại biểu chính thức.",
        icon: "🎫",
        description: "Giải pháp đón tiếp đại biểu chuẩn 5 sao, xóa bỏ hoàn toàn cuống vé giấy và tránh tình trạng ùn tắc tại sảnh tiệc.",
      },
      {
        targetId: "tour-checkin-seat",
        title: "Định Vị Số Bàn Tiệc VIP & Mã May Mắn",
        actionGesture: "👁️ Tra cứu thông tin chỗ ngồi",
        touchPoint: "Hộp thông tin vị trí chỗ ngồi và mã bốc thăm may mắn",
        instruction: "Xem trước số bàn tiệc (VD: Bàn VIP 02 - Ghế 04) để lễ tân hướng dẫn vào đúng khu vực trang trọng.",
        systemResponse: "Hệ thống tự động hiển thị số bốc thăm may mắn Gala Dinner đã được thuật toán chỉ định.",
        proTip: "Mã số may mắn sẽ tự động tham gia vòng quay Lucky Draw trực tuyến ở màn hình Biểu quyết.",
        icon: "🥂",
        description: "Giúp quý đại biểu chủ động tìm đúng bàn tiệc giao lưu cùng các đồng nghiệp cùng ban chuyên môn.",
      },
      {
        targetId: "tour-checkin-media-badge",
        title: "Đặc Quyền Soát Vé Của Ban Truyền Thông",
        actionGesture: "🛡️ Nhận diện huy hiệu Ban Truyền Thông",
        touchPoint: "Khối thông báo quyền hạn soát vé sự kiện",
        instruction: "Chỉ tài khoản thuộc Ban Truyền Thông (hoặc BQT chỉ định) mới mở được giao diện máy quét camera.",
        systemResponse: "Đối với Hội viên thông thường, hệ thống hiển thị thẻ vé xuất trình. Đối với Ban Truyền Thông, app bật camera soát vé.",
        roleNote: "Tài khoản test: ceo.truyenthong@ceo1983.com (Trưởng Ban Truyền Thông) hoặc bật nút thử nghiệm.",
        proTip: "Ban Quản Trị có thể phân công nhân sự soát vé theo từng sự kiện cụ thể trên Web CRM.",
        icon: "🛡️",
        description: "Cơ chế phân quyền RBAC đa cấp đảm bảo tính bảo mật và sự phân công nhiệm vụ chuyên nghiệp trong ban bệ.",
      },
      {
        targetId: "tour-checkin-mode-toggle",
        title: "Chế Độ Quét QR & Chạm NFC Cổng Tiệc",
        actionGesture: "📸 Hướng camera vào mã vé đại biểu",
        touchPoint: "Màn hình camera quét QR / Chạm thẻ NFC dành cho Ban Truyền Thông",
        instruction: "Nhân sự Ban Truyền Thông lia camera vào mã vé của khách. Modal thông tin đại biểu sẽ bật lên trong 0.5 giây.",
        systemResponse: "Hiển thị họ tên, doanh nghiệp, số bàn VIP và nút 'Xác Nhận Check-In' tức thì.",
        proTip: "Máy quét có hỗ trợ chế độ ngoại tuyến (Offline) tự lưu vào bộ nhớ đệm nếu sảnh tiệc mất mạng Wifi.",
        icon: "⚡",
        description: "Biến chiếc điện thoại của nhân sự Ban Truyền Thông thành máy quét soát vé chuyên nghiệp như tại sân bay.",
      },
    ],
  },
  {
    id: "association-members",
    title: "Màn hình Danh Bạ Hội Viên",
    subtitle: "200+ Chủ tịch & Tổng Giám đốc sinh năm 1983",
    route: "/association/members",
    badge: "Màn 4/10",
    iconName: "Users",
    category: "network",
    themeColor: "#0F172A",
    screenSummary: "Mạng lưới kết nối hội viên nội bộ. Tra cứu hồ sơ doanh nhân, lọc theo ngành nghề (BĐS, Xây dựng, Tài chính, F&B...) và gửi thư mời hẹn gặp 1-on-1 có mục đích.",
    mockupMockTitle: "Danh Bạ Hội Viên",
    mockupElements: [
      { id: "tour-members-search", stepIndex: 1, label: "Thanh Tìm Kiếm Đối Tác", x: 50, y: 15, badgePosition: "bottom" },
      { id: "tour-members-filter", stepIndex: 2, label: "Bộ Lọc Ngành Nghề & Ban", x: 50, y: 26, badgePosition: "bottom" },
      { id: "tour-members-card-item", stepIndex: 3, label: "Hồ Sơ Doanh Nghiệp Hội Viên", x: 50, y: 55, badgePosition: "top" },
      { id: "tour-members-connect-btn", stepIndex: 4, label: "Hẹn Gặp Giao Thương 1-on-1", x: 80, y: 68, badgePosition: "left" },
    ],
    steps: [
      {
        targetId: "tour-members-search",
        title: "Tìm Kiếm Thông Minh Bằng Tên Hoặc Công Ty",
        actionGesture: "✍️ Gõ từ khóa tìm kiếm",
        touchPoint: "Thanh tìm kiếm ở đầu danh bạ hội viên",
        instruction: "Gõ tên doanh nhân, tên công ty hoặc ngành nghề cần tìm kiếm (VD: 'Bất động sản', 'Thẩm mỹ', 'Phần mềm').",
        systemResponse: "Danh sách lọc kết quả tức thì ngay khi bạn gõ từng ký tự.",
        proTip: "Bạn cũng có thể tìm theo mã số hội viên (VD: 'M1983-001') để tìm đúng lãnh đạo câu lạc bộ.",
        icon: "🔍",
        description: "Tra cứu danh bạ tốc độ cao với thuật toán tìm kiếm tiếng Việt không dấu và có dấu đồng thời.",
      },
      {
        targetId: "tour-members-filter",
        title: "Bộ Lọc Theo Ngành Nghề & Ban Chuyên Môn",
        actionGesture: "↔️ Vuốt ngang và chạm chọn phân loại",
        touchPoint: "Hàng nút bộ lọc phân loại ngành nghề và ban chuyên trách",
        instruction: "Chạm vào các danh mục như: 'Ban Truyền Thông', 'Ban Tài Chính', 'Xây dựng', 'Công nghệ'...",
        systemResponse: "Hệ thống chỉ lọc ra các doanh nhân đang sinh hoạt trong ban ngành hoặc lĩnh vực kinh doanh đó.",
        proTip: "Bấm 'Tất cả' để quay lại danh bạ đầy đủ 200+ hội viên.",
        icon: "🎯",
        description: "Giúp quý CEO nhanh chóng tìm kiếm các đối tác trong cùng chuỗi cung ứng để xúc tiến hợp tác.",
      },
      {
        targetId: "tour-members-card-item",
        title: "Xem Chi Tiết Năng Lực Hội Viên 360°",
        actionGesture: "👆 Chạm vào thẻ hội viên",
        touchPoint: "Thẻ thông tin của hội viên trong danh sách",
        instruction: "Chạm vào tên hội viên để xem toàn bộ thông tin: Website, Sản phẩm chủ lực, Quy mô công ty và Nhu cầu hợp tác.",
        systemResponse: "Mở Modal Hồ sơ chi tiết 360° của doanh nghiệp thành viên.",
        proTip: "Hồ sơ có đính kèm danh thiếp số công khai và danh mục các bài đăng bán hàng trên Marketplace.",
        icon: "🏢",
        description: "Tìm hiểu kỹ năng lực và uy tín của đối tác trước khi tiến hành hẹn gặp hoặc ký kết hợp đồng.",
      },
      {
        targetId: "tour-members-connect-btn",
        title: "Gửi Thư Mời Hẹn Giao Thương 1-on-1",
        actionGesture: "👆 Chạm icon bắt tay 'Kết nối'",
        touchPoint: "Nút biểu tượng bắt tay màu cam/vàng trên góc thẻ hội viên",
        instruction: "Bấm nút bắt tay, nhập mục đích cuộc hẹn (VD: 'Thảo luận hợp tác cung cấp vật tư công trình') và bấm Gửi.",
        systemResponse: "Hệ thống gửi thư mời trang trọng vào Hộp thư của đối tác kèm thông báo đẩy notification.",
        proTip: "Gắn kèm mã cơ hội kinh doanh cụ thể để cuộc hẹn đạt hiệu quả giao thương cao nhất.",
        icon: "🤝",
        description: "Văn hóa kết nối thực chất của CEO 1983: Không hẹn vu vơ, mọi cuộc gặp đều có mục tiêu giao thương rõ ràng.",
      },
    ],
  },
  {
    id: "association-events",
    title: "Màn hình Sự Kiện & Hội Nghị",
    subtitle: "Lịch sinh hoạt ban, Đại hội thường niên & Gala Dinner",
    route: "/association/events",
    badge: "Màn 5/10",
    iconName: "Calendar",
    category: "events",
    themeColor: "#0284C7",
    screenSummary: "Quản trị lịch trình hoạt động hiệp hội. Đăng ký tham gia sự kiện, đặt lịch họp ban trực tuyến Zoom/Google Meet và đồng bộ vào lịch điện thoại Google/Apple Calendar.",
    mockupMockTitle: "Sự Kiện & Lịch Hoạt Động",
    mockupElements: [
      { id: "tour-events-tabs", stepIndex: 1, label: "Tab Sự Kiện & Lịch Ban", x: 50, y: 16, badgePosition: "bottom" },
      { id: "tour-events-card", stepIndex: 2, label: "Thông Tin Chi Tiết Sự Kiện", x: 50, y: 40, badgePosition: "bottom" },
      { id: "tour-events-register-btn", stepIndex: 3, label: "Nút Đăng Ký Tham Dự", x: 50, y: 62, badgePosition: "top" },
      { id: "tour-events-calendar-sync", stepIndex: 4, label: "Đồng Bộ Apple/Google Calendar", x: 50, y: 80, badgePosition: "top" },
    ],
    steps: [
      {
        targetId: "tour-events-tabs",
        title: "Chuyển Đổi Tab Sự Kiện & Cuộc Họp Ban",
        actionGesture: "👆 Chạm chuyển tab",
        touchPoint: "Thanh chuyển tab: 'Đại hội & Gala' và 'Lịch họp Ban'",
        instruction: "Chạm tab 'Lịch họp Ban' để xem các cuộc họp định kỳ của Ban Truyền Thông, Ban Tài Chính, Ban Thư Ký...",
        systemResponse: "Lọc hiển thị danh sách các phiên họp nội bộ kèm link phòng họp trực tuyến.",
        proTip: "Các cuộc họp ban có tính năng điểm danh số để tính điểm hoạt động hội viên tích cực.",
        icon: "📑",
        description: "Theo dõi đầy đủ cả 2 tuyến sự kiện: Sự kiện cộng đồng quy mô lớn và các cuộc họp ban chuyên môn sâu.",
      },
      {
        targetId: "tour-events-card",
        title: "Chi Tiết Sự Kiện, Địa Điểm & Sơ Đồ Bàn",
        actionGesture: "👆 Chạm vào thẻ sự kiện",
        touchPoint: "Thẻ sự kiện với ảnh banner lớn, thời gian và địa điểm tổ chức",
        instruction: "Xem kỹ thời gian tổ chức, địa chỉ trung tâm hội nghị và trang phục đại biểu (Dresscode).",
        systemResponse: "Mở trang chi tiết chương trình nghị sự và danh sách diễn giả nổi tiếng tham dự.",
        proTip: "Chạm vào biểu tượng bản đồ để mở chỉ đường Google Maps đến thẳng địa điểm sự kiện.",
        icon: "📍",
        description: "Nắm bắt tường tận timeline từng phần: Đón khách giao lưu, Phiên hội thảo, Khai tiệc Gala và Vinh danh.",
      },
      {
        targetId: "tour-events-register-btn",
        title: "Đăng Ký Tham Dự & Nhận Thẻ Vé Tức Thì",
        actionGesture: "👆 Chạm nút 'Đăng ký vé tham dự'",
        touchPoint: "Nút đăng ký nổi bật ở cuối mỗi thẻ sự kiện",
        instruction: "Bấm 'Đăng ký tham dự', xác nhận số lượng đại biểu đi cùng (nếu có) và bấm Hoàn tất.",
        systemResponse: "Hệ thống cấp mã vé REG-xxx và tự động đồng bộ vào Màn hình Vé Check-in của bạn.",
        proTip: "Hội viên chính thức được miễn phí vé Standard và được ưu tiên sắp xếp vị trí bàn tiệc gần sân khấu.",
        icon: "🎟️",
        description: "Thủ tục đăng ký 1 chạm tiện lợi, không cần điền lại thông tin vì hệ thống đã tự trích xuất từ hồ sơ.",
      },
      {
        targetId: "tour-events-calendar-sync",
        title: "Đồng Bộ Vào Lịch Điện Thoại 1-Chạm",
        actionGesture: "👆 Chạm 'Thêm vào Calendar'",
        touchPoint: "Nút đồng bộ lịch Google Calendar hoặc Apple Calendar",
        instruction: "Chạm nút lịch để tự động ghi lịch hẹn sự kiện vào ứng dụng Calendar mặc định trên điện thoại.",
        systemResponse: "Ứng dụng điện thoại sẽ tự động cài thông báo nhắc nhở bạn trước 1 ngày và trước 2 tiếng khai mạc.",
        proTip: "Tính năng này đặc biệt hữu ích cho các CEO bận rộn nhiều lịch công tác di chuyển.",
        icon: "⏰",
        description: "Đảm bảo bạn không bao giờ bỏ lỡ các phiên thảo luận quan trọng và sự kiện kết nối của câu lạc bộ.",
      },
    ],
  },
  {
    id: "association-opportunities",
    title: "Màn hình Cơ Hội Giao Thương B2B",
    subtitle: "Sàn chia sẻ Cung - Cầu và khớp nối dự án",
    route: "/association/opportunities",
    badge: "Màn 6/10",
    iconName: "Sparkles",
    category: "trade",
    themeColor: "#7C3AED",
    screenSummary: "Sàn trao đổi hợp tác kinh doanh nội khối CEO 1983. Đăng tin chào hàng, tìm nhà thầu phụ, kêu gọi vốn đầu tư và nhận phản hồi trực tiếp từ các chủ doanh nghiệp.",
    mockupMockTitle: "Sàn Cơ Hội Giao Thương",
    mockupElements: [
      { id: "tour-opps-stats", stepIndex: 1, label: "Tổng Giá Trị Giao Dịch", x: 50, y: 18, badgePosition: "bottom" },
      { id: "tour-opps-type-filter", stepIndex: 2, label: "Phân Loại Cung - Cầu - Hợp Tác", x: 50, y: 32, badgePosition: "bottom" },
      { id: "tour-opps-card-item", stepIndex: 3, label: "Tin Đăng Cơ Hội Kinh Doanh", x: 50, y: 56, badgePosition: "top" },
      { id: "tour-opps-create-btn", stepIndex: 4, label: "Đăng Cơ Hội Mới Của Bạn", x: 50, y: 84, badgePosition: "top" },
    ],
    steps: [
      {
        targetId: "tour-opps-stats",
        title: "Thống Kê Giá Trị Deals Đang Mở",
        actionGesture: "👁️ Quan sát chỉ số tổng",
        touchPoint: "Hộp thống kê số lượng deals và tổng giá trị VNĐ ở đầu sàn",
        instruction: "Theo dõi lượng nhu cầu giao dịch thực tế đang diễn ra trong cộng đồng doanh nhân 1983.",
        systemResponse: "Cập nhật số liệu thời gian thực theo từng tin đăng mới được kiểm duyệt.",
        proTip: "Các cơ hội có giá trị từ 500 triệu trở lên sẽ được Ban Xúc Tiến Thương Mại hỗ trợ bảo trợ pháp lý.",
        icon: "📊",
        description: "Minh chứng cho sức mạnh giao thương thực chất và hiệu quả kinh tế mà câu lạc bộ mang lại.",
      },
      {
        targetId: "tour-opps-type-filter",
        title: "Bộ Lọc Cung Cấp / Tìm Mua / Hợp Tác",
        actionGesture: "👆 Chạm chọn loại tin",
        touchPoint: "Các tab lọc: 'Tất cả', 'Cung cấp (Supply)', 'Tìm mua (Demand)', 'Hợp tác'",
        instruction: "Nếu bạn có nguồn hàng cần bán -> chọn 'Cung cấp'. Nếu đang cần tìm đối tác thi công -> chọn 'Tìm mua'.",
        systemResponse: "Lọc chính xác các cơ hội phù hợp với định hướng kinh doanh của công ty bạn.",
        proTip: "Chọn tab 'Tìm mua' để tìm kiếm các hợp đồng mua sắm ngay lập tức từ các bạn hội viên.",
        icon: "🔄",
        description: "Giúp quý doanh nghiệp tiếp cận đúng đối tượng khách hàng mục tiêu mà không mất chi phí quảng cáo.",
      },
      {
        targetId: "tour-opps-card-item",
        title: "Xem Chi Tiết Yêu Cầu & Gửi Đề Xuất",
        actionGesture: "👆 Chạm vào tiêu đề cơ hội",
        touchPoint: "Thẻ tin đăng cơ hội có gắn mác ngân sách ước tính",
        instruction: "Xem chi tiết tiêu chuẩn kỹ thuật, hạn chót nhận báo giá và thông tin người phụ trách.",
        systemResponse: "Mở màn hình chi tiết kèm nút 'Tôi Muốn Kết Nối Cơ Hội Này'.",
        proTip: "Bấm 'Tôi Muốn Kết Nối' sẽ tự động tạo cuộc trò chuyện riêng giữa bạn và chủ doanh nghiệp đăng tin.",
        icon: "🤝",
        description: "Khớp nối cung cầu nhanh chóng, minh bạch và an toàn giữa những người bạn đồng niên tin cậy.",
      },
      {
        targetId: "tour-opps-create-btn",
        title: "Đăng Cơ Hội Hợp Tác Mới",
        actionGesture: "👆 Chạm nút 'Đăng cơ hội ngay →'",
        touchPoint: "Nút đăng cơ hội màu tím nổi bật ở cuối danh sách",
        instruction: "Điền tiêu đề, mô tả nhu cầu, giá trị dự kiến và tải ảnh sản phẩm minh họa rồi bấm 'Đăng tin'.",
        systemResponse: "Tin đăng được gửi vào hàng đợi và thông báo ngay đến toàn bộ hội viên phù hợp ngành nghề.",
        proTip: "Nên mô tả rõ tiêu chuẩn nghiệm thu và điều kiện thanh toán để nhận được báo giá chuẩn nhất.",
        icon: "✨",
        description: "Biến cộng đồng 200+ CEO thành mạng lưới đối tác và phòng kinh doanh ngoại lực hùng hậu của bạn.",
      },
    ],
  },
  {
    id: "association-products",
    title: "Màn hình Chợ B2B Marketplace",
    subtitle: "Gian hàng số, sản phẩm sỉ & ưu đãi nội khối",
    route: "/association/products",
    badge: "Màn 7/10",
    iconName: "ShoppingBag",
    category: "trade",
    themeColor: "#D97706",
    screenSummary: "Sàn thương mại điện tử nội bộ. Hội viên quảng bá giải pháp doanh nghiệp, vật tư công trình, dịch vụ tư vấn với chính sách giá ưu đãi độc quyền cho thành viên CEO 1983.",
    mockupMockTitle: "Chợ B2B Marketplace",
    mockupElements: [
      { id: "tour-market-tabs", stepIndex: 1, label: "Tab Chợ & Mục Của Tôi", x: 50, y: 16, badgePosition: "bottom" },
      { id: "tour-market-grid", stepIndex: 2, label: "Gian Hàng Sản Phẩm Hội Viên", x: 50, y: 44, badgePosition: "bottom" },
      { id: "tour-market-detail-quote", stepIndex: 3, label: "Báo Giá & Chiết Khấu VIP", x: 75, y: 60, badgePosition: "left" },
      { id: "tour-market-post-btn", stepIndex: 4, label: "Đăng Bán Sản Phẩm Mới", x: 50, y: 82, badgePosition: "top" },
    ],
    steps: [
      {
        targetId: "tour-market-tabs",
        title: "Tab Chợ Chung & Quản Lý 'Mục Của Tôi'",
        actionGesture: "👆 Chạm chuyển tab",
        touchPoint: "2 tab lớn trên đầu trang: 'Chợ Marketplace' và 'Mục của tôi'",
        instruction: "Chuyển sang tab 'Mục của tôi' để theo dõi tất cả sản phẩm bạn đang chào bán và đơn báo giá của bạn.",
        systemResponse: "Hiển thị trung tâm quản trị gian hàng của riêng công ty bạn.",
        proTip: "Tab 'Mục của tôi' có nút 'Quảng cáo tài trợ' để bạn đặt banner nổi bật lên đầu trang chủ.",
        icon: "🏬",
        description: "Quản lý sản phẩm và đơn hàng cực kỳ tinh gọn ngay trên điện thoại di động.",
      },
      {
        targetId: "tour-market-grid",
        title: "Gian Hàng Sản Phẩm & Dịch Vụ Đa Ngành",
        actionGesture: "↕️ Cuộn xem danh sách sản phẩm",
        touchPoint: "Lưới hiển thị sản phẩm với hình ảnh bắt mắt và giá bán niêm yết",
        instruction: "Duyệt tìm sản phẩm thiết bị, nguyên vật liệu hoặc dịch vụ phần mềm đang có chính sách giá ưu đãi.",
        systemResponse: "Hiển thị chi tiết phần trăm giảm giá dành riêng cho hội viên có thẻ VIP CEO 1983.",
        proTip: "Các sản phẩm có huy hiệu 'Xác thực bởi CLB' là các sản phẩm đã được kiểm định chất lượng nghiêm ngặt.",
        icon: "📦",
        description: "Ưu tiên dùng hàng của nhau, gia tăng doanh số và tạo dòng tiền tuần hoàn mạnh mẽ trong câu lạc bộ.",
      },
      {
        targetId: "tour-market-detail-quote",
        title: "Yêu Cầu Báo Giá Sỉ & Nhắn Tin Thương Lượng",
        actionGesture: "👆 Chạm nút 'Yêu cầu báo giá' hoặc 'Nhắn tin'",
        touchPoint: "Nút hành động trên từng thẻ sản phẩm",
        instruction: "Bấm 'Nhắn tin' để mở cuộc hội thoại chat trực tiếp với người đại diện công ty cung cấp.",
        systemResponse: "Hệ thống tự động đính kèm hình ảnh và mã sản phẩm vào khung chat để đôi bên dễ trao đổi.",
        proTip: "Bạn có thể gửi yêu cầu chiết khấu đơn hàng lớn trực tiếp qua biểu mẫu Báo giá sỉ.",
        icon: "💬",
        description: "Thương lượng trực tiếp với lãnh đạo cao nhất của đơn vị bán mà không cần qua môi giới trung gian.",
      },
      {
        targetId: "tour-market-post-btn",
        title: "Đăng Bán Sản Phẩm Mới Lên Gian Hàng",
        actionGesture: "👆 Chạm nút 'Đăng bán sản phẩm'",
        touchPoint: "Nút 'Đăng tin sản phẩm' tại tab Mục của tôi",
        instruction: "Chụp ảnh sản phẩm, điền tên hàng, giá niêm yết, phần trăm giảm giá cho hội viên và bấm Lưu.",
        systemResponse: "Sản phẩm xuất hiện ngay lập tức trên Marketplace để 200+ CEO cùng tham khảo mua sắm.",
        proTip: "Tải lên ảnh vuông tỉ lệ 1:1 rõ nét để gian hàng của bạn trông chuyên nghiệp và thu hút nhất.",
        icon: "🏷️",
        description: "Mở rộng kênh phân phối B2B chất lượng cao với chi phí 0 đồng dành riêng cho hội viên chính thức.",
      },
    ],
  },
  {
    id: "association-voting",
    title: "Màn hình Bầu Cử & Lucky Draw",
    subtitle: "Bỏ phiếu điện tử bảo mật & Vòng quay may mắn Gala",
    route: "/association/voting",
    badge: "Màn 8/10",
    iconName: "Vote",
    category: "core",
    themeColor: "#059669",
    screenSummary: "Phân hệ biểu quyết dân chủ và minh bạch của CLB CEO 1983. Bỏ phiếu bầu Ban Chấp Hành, biểu quyết các nghị quyết lớn và hồi hộp cùng Vòng quay số may mắn Gala Dinner.",
    mockupMockTitle: "Bầu Cử & Biểu Quyết",
    mockupElements: [
      { id: "tour-voting-tabs", stepIndex: 1, label: "Tab Biểu Quyết & Lucky Draw", x: 50, y: 16, badgePosition: "bottom" },
      { id: "tour-voting-poll-card", stepIndex: 2, label: "Chi Tiết Đề Án Bỏ Phiếu", x: 50, y: 38, badgePosition: "bottom" },
      { id: "tour-voting-submit-btn", stepIndex: 3, label: "Thao Tác Bỏ Phiếu Kín", x: 50, y: 62, badgePosition: "top" },
      { id: "tour-voting-lucky-draw", stepIndex: 4, label: "Vòng Quay Số May Mắn Gala", x: 50, y: 82, badgePosition: "top" },
    ],
    steps: [
      {
        targetId: "tour-voting-tabs",
        title: "Tab Bầu Cử Ban Chấp Hành & Lucky Draw",
        actionGesture: "👆 Chạm chọn tab",
        touchPoint: "Thanh chuyển tab giữa 'Biểu quyết đại hội' và 'Quay số trúng thưởng'",
        instruction: "Chạm 'Quay số trúng thưởng' khi đến phần trao giải Gala Dinner để xem trực tiếp lồng quay số.",
        systemResponse: "Mở giao diện Vòng quay số may mắn thời gian thực kết nối với màn hình LED sân khấu.",
        proTip: "Mã số vé may mắn của bạn tại Màn hình Vé Check-in sẽ tự động nằm trong thùng phiếu điện tử.",
        icon: "🗳️",
        description: "Kết hợp giữa nghiệp vụ quản trị nghiêm cẩn và không khí sôi động, hào hứng của đêm hội ngộ doanh nhân.",
      },
      {
        targetId: "tour-voting-poll-card",
        title: "Đề Án Biểu Quyết & Danh Sách Ứng Viên",
        actionGesture: "👁️ Đọc nội dung đề án và danh sách ứng viên",
        touchPoint: "Thẻ cuộc bỏ phiếu với trạng thái 'Đang mở' và thời hạn đếm ngược",
        instruction: "Xem kỹ lý lịch trích ngang của các ứng cử viên Ban Chấp Hành hoặc nội dung sửa đổi Điều lệ CLB.",
        systemResponse: "Hiển thị tỷ lệ phần trăm cử tri đã tham gia bỏ phiếu trực tiếp.",
        proTip: "Mỗi hội viên chính thức chỉ có 01 phiếu bầu duy nhất theo nguyên tắc bình đẳng dân chủ.",
        icon: "📜",
        description: "Toàn bộ dữ liệu phiếu bầu được mã hóa chống gian lận và có nhật ký kiểm toán không thể can thiệp.",
      },
      {
        targetId: "tour-voting-submit-btn",
        title: "Tích Chọn & Xác Nhận Bỏ Phiếu Kín",
        actionGesture: "👆 Tích chọn phương án và bấm 'Gửi phiếu bầu'",
        touchPoint: "Các ô tích chọn ứng viên và nút xác nhận bỏ phiếu",
        instruction: "Tích chọn ứng viên bạn tín nhiệm, nhập nhận xét đóng góp (nếu có) và bấm 'Gửi phiếu bầu'.",
        systemResponse: "Hệ thống ghi nhận phiếu thành công và chuyển trạng thái của bạn sang 'Đã hoàn tất bỏ phiếu'.",
        roleNote: "Chỉ các tài khoản hội viên chính thức (không bị nợ hội phí) mới được kích hoạt quyền bầu cử.",
        proTip: "Sau khi gửi phiếu, bạn có thể xem biểu đồ kết quả biểu quyết trực quan sau khi hết giờ bỏ phiếu.",
        icon: "✅",
        description: "Thao tác biểu quyết nhanh chóng, bảo mật tuyệt đối danh tính người bỏ phiếu theo đúng chuẩn mực.",
      },
      {
        targetId: "tour-voting-lucky-draw",
        title: "Hồi Hộp Cùng Vòng Quay May Mắn Gala",
        actionGesture: "🎉 Quan sát lồng quay số may mắn",
        touchPoint: "Màn hình vòng quay bánh xe số may mắn Gala Dinner",
        instruction: "Khi MC tuyên bố quay giải, bạn theo dõi các con số nhảy múa trên màn hình điện thoại.",
        systemResponse: "Nếu mã vé của bạn trùng khớp giải thưởng, màn hình điện thoại sẽ nổ pháo hoa chúc mừng!",
        proTip: "Nhớ giữ kết nối mạng Wifi/4G ổn định để nhận thông báo trúng giải ngay tức thì.",
        icon: "🎁",
        description: "Tính năng tương tác thực tế kết nối trực tiếp điện thoại cá nhân với màn hình máy chiếu sân khấu chính.",
      },
    ],
  },
  {
    id: "association-messages",
    title: "Màn hình Tin Nhắn & Hội Thoại",
    subtitle: "Hộp thư đối tác B2B & Nhóm thảo luận các Ban",
    route: "/association/messages",
    badge: "Màn 9/10",
    iconName: "MessageSquare",
    category: "network",
    themeColor: "#003B95",
    screenSummary: "Không gian giao tiếp nội bộ an toàn và bảo mật. Trò chuyện 1-1 với các chủ doanh nghiệp, trao đổi tài liệu hợp đồng kinh doanh và tham gia nhóm chat chuyên trách của các ban.",
    mockupMockTitle: "Hộp Thư B2B CEO 1983",
    mockupElements: [
      { id: "tour-msg-tabs", stepIndex: 1, label: "Tab Cá Nhân & Nhóm Ban", x: 50, y: 16, badgePosition: "bottom" },
      { id: "tour-msg-thread", stepIndex: 2, label: "Danh Sách Cuộc Hội Thoại", x: 50, y: 45, badgePosition: "bottom" },
      { id: "tour-msg-chat-tools", stepIndex: 3, label: "Gửi File Báo Giá & Danh Thiếp", x: 50, y: 72, badgePosition: "top" },
      { id: "tour-msg-new-btn", stepIndex: 4, label: "Tạo Nhóm Thảo Luận Mới", x: 88, y: 88, badgePosition: "left" },
    ],
    steps: [
      {
        targetId: "tour-msg-tabs",
        title: "Hộp Thư Cá Nhân & Nhóm Ban Chuyên Môn",
        actionGesture: "👆 Chạm chuyển giữa Tin nhắn và Nhóm ban",
        touchPoint: "Thanh tab phân loại hội thoại: 'Tin nhắn' và 'Nhóm ban'",
        instruction: "Chạm tab 'Nhóm ban' để vào nhóm thảo luận riêng của Ban Truyền Thông, Ban Tài Chính hoặc Ban Thư Ký.",
        systemResponse: "Hiển thị các phòng thảo luận chuyên đề mà bạn là thành viên chính thức.",
        proTip: "Các thông báo quan trọng của Ban Chủ Nhiệm sẽ được ghim lên đầu nhóm chat.",
        icon: "👥",
        description: "Tách bạch rõ ràng giữa các cuộc trao đổi công việc riêng tư và thông tin điều hành tập thể.",
      },
      {
        targetId: "tour-msg-thread",
        title: "Mở Cuộc Trò Chuyện & Xem Lịch Sử Hẹn",
        actionGesture: "👆 Chạm vào cuộc trò chuyện",
        touchPoint: "Một hội thoại trong danh sách có avatar và tin nhắn mới nhất",
        instruction: "Chạm vào hội thoại để tiếp tục thảo luận hợp đồng, trao đổi tiến độ dự án hoặc hẹn lịch gặp mặt.",
        systemResponse: "Mở khung chat bảo mật với lịch sử tin nhắn được lưu trữ trên máy chủ an toàn.",
        proTip: "Các tin nhắn đến từ thư mời kết nối sẽ có huy hiệu 'Lời mời giao thương' nổi bật.",
        icon: "💬",
        description: "Giao tiếp không bị nhiễu loạn bởi tin nhắn rác bên ngoài, 100% đối tác trò chuyện đều là hội viên đã xác thực.",
      },
      {
        targetId: "tour-msg-chat-tools",
        title: "Đính Kèm Danh Thiếp, Ảnh & File Hợp Đồng",
        actionGesture: "👆 Chạm icon dấu cộng (+) hoặc kẹp giấy",
        touchPoint: "Thanh công cụ gửi tệp đính kèm ở chân khung chat",
        instruction: "Bấm icon tệp để gửi nhanh danh thiếp điện tử của bạn hoặc tài liệu hồ sơ năng lực công ty (PDF).",
        systemResponse: "Tài liệu được mã hóa gửi tức thì sang điện thoại đối tác để họ tải về xem trực tiếp.",
        proTip: "Bạn có thể gửi nhanh vị trí địa chỉ văn phòng để đối tác dễ dàng tìm đường ghé thăm công ty.",
        icon: "📎",
        description: "Bộ công cụ chuyên nghiệp phục vụ tối đa cho các cuộc đàm phán hợp đồng giữa các chủ doanh nghiệp.",
      },
      {
        targetId: "tour-msg-new-btn",
        title: "Tạo Nhóm Thảo Luận Dự Án Mới",
        actionGesture: "👆 Chạm nút bút soạn tin / Tạo nhóm",
        touchPoint: "Nút hành động tạo hội thoại mới ở góc phải màn hình",
        instruction: "Bấm nút tạo nhóm, đặt tên nhóm (VD: 'Dự án Cụm Công nghiệp 1983') và tích chọn các CEO tham gia.",
        systemResponse: "Hệ thống tự động kích hoạt phòng chat nhóm và gửi thông báo mời tham gia tới các thành viên.",
        proTip: "Trưởng nhóm có quyền thêm hoặc mời thành viên ra khỏi nhóm để bảo mật thông tin dự án.",
        icon: "➕",
        description: "Khởi tạo nhanh chóng các liên minh doanh nghiệp và nhóm hợp tác đầu tư theo từng chuyên đề cụ thể.",
      },
    ],
  },
  {
    id: "association-profile",
    title: "Màn hình Hồ Sơ Doanh Nhân & Cài Đặt",
    subtitle: "Chủ đề lễ hội, Trung tâm hướng dẫn & Hotline các Ban",
    route: "/association/profile",
    badge: "Màn 10/10",
    iconName: "User",
    category: "core",
    themeColor: "#003B95",
    screenSummary: "Trung tâm quản trị tài khoản và cài đặt trải nghiệm. Xem hồ sơ 360°, đổi giao diện Lễ Hội theo mùa (Tết, Trung Thu, Noel), mở Trung tâm Hướng dẫn sử dụng và gọi Hotline các ban chuyên môn.",
    mockupMockTitle: "Hồ Sơ & Cài Đặt",
    mockupElements: [
      { id: "tour-profile-card", stepIndex: 1, label: "Hồ Sơ Doanh Nhân 360°", x: 50, y: 22, badgePosition: "bottom" },
      { id: "tour-profile-theme", stepIndex: 2, label: "Đổi Giao Diện & Chủ Đề Lễ Hội", x: 50, y: 44, badgePosition: "bottom" },
      { id: "tour-profile-guide-btn", stepIndex: 3, label: "Trung Tâm Hướng Dẫn Sử Dụng", x: 50, y: 65, badgePosition: "top" },
      { id: "tour-profile-hotline-btn", stepIndex: 4, label: "Liên Hệ Hotline 5 Ban Chuyên Môn", x: 50, y: 84, badgePosition: "top" },
    ],
    steps: [
      {
        targetId: "tour-profile-card",
        title: "Hồ Sơ Doanh Nhân & Thông Tin Định Danh",
        actionGesture: "👆 Chạm vào vùng thông tin cá nhân",
        touchPoint: "Khối hồ sơ có avatar, họ tên, mã hội viên M1983 và email",
        instruction: "Kiểm tra tình trạng kích hoạt tài khoản, niên liễm hội phí và chức danh trong câu lạc bộ.",
        systemResponse: "Hiển thị chi tiết tình trạng hợp đồng hội viên và ngày gia hạn tiếp theo.",
        proTip: "Bấm 'Đổi mật khẩu' để tăng cường bảo mật cho tài khoản của bạn định kỳ 3 tháng một lần.",
        icon: "👤",
        description: "Hồ sơ điện tử chuẩn xác chứng nhận tư cách hội viên chính thức của CLB Doanh Nhân CEO 1983.",
      },
      {
        targetId: "tour-profile-theme",
        title: "Tùy Biến Giao Diện Sáng / Tối & Lễ Hội",
        actionGesture: "👆 Chạm nút 'Chủ đề giao diện'",
        touchPoint: "Mục cài đặt Giao diện (Theme Selector)",
        instruction: "Chạm để chuyển đổi linh hoạt giữa: Giao diện Sáng thanh lịch, Tối sang trọng hoặc Chủ đề Lễ Hội rực rỡ.",
        systemResponse: "Màu sắc toàn bộ ứng dụng biến đổi ngay lập tức theo phong cách bạn lựa chọn.",
        proTip: "Vào các dịp Tết Nguyên Đán hoặc Quốc Khánh, chủ đề Lễ Hội sẽ có hiệu ứng hoa đào, pháo hoa đặc biệt.",
        icon: "🎨",
        description: "Cá nhân hóa trải nghiệm theo sở thích và điều kiện ánh sáng môi trường làm việc của từng doanh nhân.",
      },
      {
        targetId: "tour-profile-guide-btn",
        title: "Trung Tâm Hướng Dẫn Sử Dụng 10 Tính Năng",
        actionGesture: "👆 Chạm mục 'Hướng dẫn sử dụng'",
        touchPoint: "Mục 'Hướng dẫn sử dụng ứng dụng (10 chức năng)'",
        instruction: "Chạm vào đây bất kỳ lúc nào để mở Cẩm nang tương tác trực quan hoặc xem lại chỉ dẫn từng màn hình.",
        systemResponse: "Mở Modal Trung tâm hướng dẫn sử dụng mô phỏng chi tiết chuẩn app ngân hàng.",
        proTip: "Bạn có thể bấm 'Chỉ dẫn trực tiếp' để app tự động dẫn bạn đi từng bước trên các màn hình thực tế.",
        icon: "📖",
        description: "Cẩm nang số luôn sẵn sàng hỗ trợ các CEO làm chủ mọi tính năng công nghệ của ứng dụng trong tầm tay.",
      },
      {
        targetId: "tour-profile-hotline-btn",
        title: "Hotline Trực Tiếp 5 Ban Chuyên Môn",
        actionGesture: "👆 Chạm mục 'Liên hệ Ban Chuyên Môn'",
        touchPoint: "Mục hỗ trợ liên hệ Ban Truyền Thông, Ban Thư Ký, Ban Thành Viên...",
        instruction: "Bấm để mở danh bạ điện thoại và Zalo OA trực tiếp của các Trưởng ban phụ trách.",
        systemResponse: "Bật popup gọi điện hoặc mở chat Zalo trực tiếp tới nhân sự phụ trách ban tương ứng.",
        roleNote: "Ban Truyền Thông hỗ trợ soát vé; Ban Thư Ký hỗ trợ thủ tục hội viên; Ban Tài Chính hỗ trợ hóa đơn hội phí.",
        proTip: "Tổng đài hỗ trợ 24/7 luôn sẵn sàng lắng nghe mọi ý kiến đóng góp xây dựng cộng đồng của bạn.",
        icon: "📞",
        description: "Cầu nối trực tiếp và thông suốt giữa các hội viên và Ban Chấp Hành điều hành câu lạc bộ.",
      },
    ],
  },
  {
    id: "association-library",
    title: "Màn hình Kho Văn Bản & Kỷ Yếu",
    subtitle: "Điều lệ hiệp hội, Quy chế hoạt động & Tài liệu pháp lý",
    route: "/association/library",
    badge: "Màn Thư Viện",
    iconName: "BookOpen",
    category: "core",
    themeColor: "#0369A1",
    screenSummary: "Kho lưu trữ văn bản số chính thức của CLB Doanh Nhân CEO 1983. Tải điều lệ, quy chế ban bệ, kỷ yếu doanh nghiệp và biểu mẫu pháp lý.",
    mockupMockTitle: "Kho Văn Bản & Kỷ Yếu",
    mockupElements: [
      { id: "tour-lib-search", stepIndex: 1, label: "Tìm Kiếm Tài Liệu", x: 50, y: 15, badgePosition: "bottom" },
      { id: "tour-lib-list", stepIndex: 2, label: "Danh Sách Văn Bản & Quy Chế", x: 50, y: 45, badgePosition: "bottom" },
      { id: "tour-lib-download-btn", stepIndex: 3, label: "Nút Tải Xuống PDF", x: 80, y: 55, badgePosition: "left" },
      { id: "tour-lib-share-btn", stepIndex: 4, label: "Chia Sẻ Liên Kết Văn Bản", x: 50, y: 80, badgePosition: "top" },
    ],
    steps: [
      {
        targetId: "tour-lib-search",
        title: "Tìm Kiếm Tài Liệu & Nghị Quyết Nhanh",
        actionGesture: "✍️ Gõ từ khóa tìm kiếm",
        touchPoint: "Thanh tìm kiếm tài liệu ở đầu trang",
        instruction: "Gõ 'Điều lệ', 'Quy chế', 'Kỷ yếu' hoặc tên văn bản cần tra cứu.",
        systemResponse: "Hệ thống lọc tức thì các tệp PDF và biểu mẫu liên quan.",
        icon: "🔍",
        description: "Tra cứu nhanh các văn bản pháp quy điều hành hiệp hội.",
      },
      {
        targetId: "tour-lib-list",
        title: "Danh Sách Văn Bản Điều Lệ & Kỷ Yếu",
        actionGesture: "👆 Chạm vào tên tài liệu",
        touchPoint: "Các thẻ văn bản trong danh sách",
        instruction: "Chạm vào văn bản để xem bản tóm tắt nội dung, ngày ban hành và đơn vị ký duyệt.",
        systemResponse: "Mở bản xem trước tài liệu kèm dung lượng tệp tin.",
        icon: "📄",
        description: "Toàn bộ tài liệu chính thức được số hóa và ký duyệt số.",
      },
      {
        targetId: "tour-lib-download-btn",
        title: "Tải Xuống Tệp PDF Về Máy",
        actionGesture: "👆 Chạm icon Tải xuống",
        touchPoint: "Nút biểu tượng tải về cạnh mỗi tài liệu",
        instruction: "Bấm icon tải xuống để lưu tệp PDF về máy điện thoại hoặc mở đọc trên trình duyệt.",
        systemResponse: "Bắt đầu tải xuống tệp tin gốc với độ nét cao.",
        icon: "💾",
        description: "Lưu trữ offline để đọc mọi lúc mà không cần mạng internet.",
      },
      {
        targetId: "tour-lib-share-btn",
        title: "Chia Sẻ Liên Kết Cho Đồng Nghiệp",
        actionGesture: "👆 Chạm nút Chia sẻ",
        touchPoint: "Nút chia sẻ liên kết văn bản",
        instruction: "Bấm nút chia sẻ để copy đường link gửi qua Zalo cho đối tác và ban lãnh đạo.",
        systemResponse: "Đã sao chép liên kết vào bộ nhớ tạm.",
        icon: "🔗",
        description: "Lan tỏa thông điệp và quy định chung của cộng đồng doanh nhân.",
      },
    ],
  },
  {
    id: "association-notifications",
    title: "Màn hình Trung Tâm Thông Báo",
    subtitle: "Tin tức điều hành từ Ban Thư ký & Nhắc nhở quyền lợi",
    route: "/association/notifications",
    badge: "Màn Thông Báo",
    iconName: "Bell",
    category: "core",
    themeColor: "#E11D48",
    screenSummary: "Hộp thư thông báo chính thức từ Ban Thư ký và Ban Điều hành. Nhắc việc, lịch họp ban, xác nhận vé sự kiện và tình trạng hội phí.",
    mockupMockTitle: "Trung Tâm Thông Báo",
    mockupElements: [
      { id: "tour-notif-filter", stepIndex: 1, label: "Bộ Lọc Chưa Đọc / Đã Đọc", x: 50, y: 16, badgePosition: "bottom" },
      { id: "tour-notif-card", stepIndex: 2, label: "Nội Dung Bản Tin & Nhắc Việc", x: 50, y: 45, badgePosition: "bottom" },
      { id: "tour-notif-action", stepIndex: 3, label: "Hành Động Đi Kèm (Xem Vé, Đóng Phí)", x: 80, y: 55, badgePosition: "left" },
      { id: "tour-notif-read-all", stepIndex: 4, label: "Đánh Dấu Đã Đọc Tất Cả", x: 85, y: 16, badgePosition: "left" },
    ],
    steps: [
      {
        targetId: "tour-notif-filter",
        title: "Lọc Thông Báo Chưa Đọc & Khẩn Cấp",
        actionGesture: "👆 Chạm chọn tab Chưa đọc",
        touchPoint: "Thanh tab bộ lọc thông báo trên đầu màn hình",
        instruction: "Chạm tab 'Chưa đọc' để chỉ hiển thị các tin nhắn quan trọng bạn chưa mở.",
        systemResponse: "Hiển thị danh sách các thông báo mới nhất cần xử lý.",
        icon: "🎯",
        description: "Giúp quý lãnh đạo không bị bỏ sót các công việc và sự kiện quan trọng.",
      },
      {
        targetId: "tour-notif-card",
        title: "Chi Tiết Thông Báo & Nhắc Nhở",
        actionGesture: "👆 Chạm vào thông báo",
        touchPoint: "Thẻ thông báo có tiêu đề và ngày giờ gửi",
        instruction: "Chạm vào thông báo để đọc chi tiết nội dung chỉ đạo từ Ban Thư ký.",
        systemResponse: "Mở chi tiết và tự động đánh dấu đã đọc.",
        icon: "📩",
        description: "Kênh truyền thông nội bộ chính thống, loại bỏ tin giả và tin rác.",
      },
      {
        targetId: "tour-notif-action",
        title: "Thực Hiện Hành Động Trực Tiếp",
        actionGesture: "👆 Chạm nút hành động",
        touchPoint: "Nút hành động trong thông báo (VD: Xem vé, Xem sự kiện, Đóng phí)",
        instruction: "Bấm nút hành động để chuyển thẳng tới phân hệ nghiệp vụ tương ứng.",
        systemResponse: "Điều hướng siêu tốc tới đúng màn hình liên quan.",
        icon: "⚡",
        description: "Xử lý công việc 1 chạm tiện lợi không cần thao tác nhiều bước.",
      },
      {
        targetId: "tour-notif-read-all",
        title: "Đánh Dấu Đã Đọc Toàn Bộ",
        actionGesture: "👆 Chạm nút 'Đã đọc tất cả'",
        touchPoint: "Nút đánh dấu đã đọc ở góc phải thanh tiêu đề",
        instruction: "Bấm nút này để xóa toàn bộ chấm đỏ thông báo chưa đọc.",
        systemResponse: "Cập nhật số đếm thông báo về 0 và xóa chấm đỏ.",
        icon: "✅",
        description: "Dọn dẹp hộp thư thông báo nhanh chóng khi bạn đã nắm rõ tin tức.",
      },
    ],
  },
  {
    id: "events-admin",
    title: "Màn hình Quản Trị Sự Kiện (Ban Tổ Chức)",
    subtitle: "Tạo sự kiện mới, quản lý vé đăng ký & sơ đồ bàn VIP",
    route: "/events",
    badge: "CRM Ngoài 1/6",
    iconName: "CalendarDays",
    category: "events",
    themeColor: "#0284C7",
    screenSummary: "Bàn điều phối sự kiện chuyên nghiệp dành cho Ban Tổ Chức & Ban Truyền Thông. Tạo sự kiện, quản trị đại biểu, phân quyền soát vé và xuất danh sách Excel.",
    mockupMockTitle: "Quản Trị Sự Kiện CRM",
    mockupElements: [
      { id: "tour-admin-event-create", stepIndex: 1, label: "Nút Tạo Sự Kiện Mới", x: 85, y: 15, badgePosition: "left" },
      { id: "tour-admin-event-table", stepIndex: 2, label: "Danh Sách Sự Kiện Đang Mở", x: 50, y: 40, badgePosition: "bottom" },
      { id: "tour-admin-event-registrations", stepIndex: 3, label: "Quản Lý Danh Sách Đại Biểu", x: 50, y: 65, badgePosition: "top" },
      { id: "tour-admin-event-export", stepIndex: 4, label: "Xuất File Excel Điểm Danh", x: 80, y: 85, badgePosition: "left" },
    ],
    steps: [
      {
        targetId: "tour-admin-event-create",
        title: "Tạo Mới Sự Kiện & Hội Nghị",
        actionGesture: "👆 Chạm nút '+ Tạo sự kiện'",
        touchPoint: "Nút '+ Tạo sự kiện mới' màu xanh nổi bật ở góc trên bên phải",
        instruction: "Bấm nút tạo sự kiện, điền Tên sự kiện, Ngày giờ tổ chức, Địa điểm, Sức chứa và Trang phục (Dresscode).",
        systemResponse: "Mở Wizard Tạo sự kiện đa bước chuẩn quốc tế.",
        roleNote: "Chỉ tài khoản Ban Quản Trị hoặc Ban Tổ Chức mới có thẩm quyền thực hiện.",
        icon: "➕",
        description: "Khởi tạo nhanh chóng các phiên hội thảo, đại hội thường niên và giải Golf.",
      },
      {
        targetId: "tour-admin-event-table",
        title: "Bảng Điều Phối Sự Kiện Thời Gian Thực",
        actionGesture: "👁️ Quan sát trạng thái các sự kiện",
        touchPoint: "Bảng danh sách sự kiện hiển thị số lượng vé đã đăng ký và doanh thu vé",
        instruction: "Theo dõi số lượng đại biểu đăng ký theo thời gian thực (VD: 150/200 vé).",
        systemResponse: "Cập nhật tiến độ đăng ký vé tự động.",
        icon: "📊",
        description: "Nắm bắt tình hình quan tâm của hội viên để điều chỉnh quy mô hội trường.",
      },
      {
        targetId: "tour-admin-event-registrations",
        title: "Quản Lý Đại Biểu & Sắp Xếp Bàn Tiệc VIP",
        actionGesture: "👆 Chạm nút 'Danh sách đăng ký'",
        touchPoint: "Nút xem danh sách đại biểu trên từng hàng sự kiện",
        instruction: "Bấm để phân bổ số bàn tiệc VIP (Bàn 01, Bàn 02), gắn mã bốc thăm Gala và duyệt vé VIP.",
        systemResponse: "Mở danh sách chi tiết từng đại biểu tham dự.",
        icon: "👥",
        description: "Sắp xếp chỗ ngồi chu đáo theo đúng nghi thức đón tiếp lãnh đạo.",
      },
      {
        targetId: "tour-admin-event-export",
        title: "Xuất Danh Sách Điểm Danh Dạng Excel",
        actionGesture: "👆 Chạm nút 'Xuất Excel / CSV'",
        touchPoint: "Nút xuất dữ liệu ở thanh công cụ",
        instruction: "Bấm nút để tải toàn bộ danh sách khách mời phục vụ in thẻ đeo và chuẩn bị quà tặng.",
        systemResponse: "Tự động tải xuống tệp .csv / .xlsx chuẩn UTF-8 tiếng Việt.",
        icon: "📥",
        description: "Phục vụ công tác hậu cần và lễ tân tiếp đón chuyên nghiệp tại sảnh.",
      },
    ],
  },
  {
    id: "members-admin",
    title: "Màn hình Quản Lý Hội Viên CRM (Ban Hội Viên)",
    subtitle: "Hồ sơ 200+ CEO, phê duyệt đơn kết nạp & cấp mã M1983",
    route: "/members",
    badge: "CRM Ngoài 2/6",
    iconName: "Users",
    category: "network",
    themeColor: "#0F172A",
    screenSummary: "Hệ thống CRM quản lý vòng đời hội viên của Hiệp hội CEO 1983. Tiếp nhận đơn đăng ký, thẩm định doanh nghiệp, phê duyệt kết nạp và cấp mã định danh.",
    mockupMockTitle: "Quản Lý Hội Viên CRM",
    mockupElements: [
      { id: "tour-admin-member-search", stepIndex: 1, label: "Tra Cứu Hồ Sơ CRM", x: 50, y: 15, badgePosition: "bottom" },
      { id: "tour-admin-member-approval", stepIndex: 2, label: "Phê Duyệt Kết Nạp Mới", x: 80, y: 35, badgePosition: "left" },
      { id: "tour-admin-member-tier", stepIndex: 3, label: "Phân Hạng Thẻ & Ban Chuyên Môn", x: 50, y: 60, badgePosition: "top" },
      { id: "tour-admin-member-export", stepIndex: 4, label: "Xuất Kỷ Yếu Danh Bạ", x: 80, y: 85, badgePosition: "left" },
    ],
    steps: [
      {
        targetId: "tour-admin-member-search",
        title: "Tra Cứu Hồ Sơ Hội Viên Đa Chiều",
        actionGesture: "✍️ Gõ từ khóa tìm kiếm",
        touchPoint: "Thanh tìm kiếm hội viên theo Tên, Công ty, Mã M1983 hoặc SĐT",
        instruction: "Tra cứu nhanh hồ sơ năng lực công ty và quá trình sinh hoạt của từng doanh nhân.",
        systemResponse: "Lọc kết quả tức thì trong 0.2 giây.",
        icon: "🔍",
        description: "Quản trị dữ liệu hồ sơ hội viên tập trung và bảo mật.",
      },
      {
        targetId: "tour-admin-member-approval",
        title: "Thẩm Định & Phê Duyệt Kết Nạp Hội Viên",
        actionGesture: "👆 Chạm nút 'Phê duyệt'",
        touchPoint: "Cột hành động trên các hồ sơ đang ở trạng thái 'Chờ duyệt'",
        instruction: "Kiểm tra điều kiện năm sinh 1983 và giấy phép kinh doanh, sau đó bấm 'Phê duyệt'.",
        systemResponse: "Hệ thống tự sinh mã M1983-xxx và gửi email chào mừng chính thức.",
        roleNote: "Thẩm quyền thuộc Ban Hội Viên và Chủ Tịch Hiệp Hội.",
        icon: "🎖️",
        description: "Đảm bảo chất lượng và chuẩn mực cao nhất cho cộng đồng thành viên.",
      },
      {
        targetId: "tour-admin-member-tier",
        title: "Phân Bổ Hạng Thẻ VIP & Ban Chuyên Môn",
        actionGesture: "👆 Chạm chỉnh sửa phân ban",
        touchPoint: "Mục gán Ban Chuyên Môn (Ban Truyền Thông, Ban Tài Chính, Ban Thư Ký...)",
        instruction: "Chỉ định hội viên vào đúng ban chuyên môn để tham gia các phiên họp chuyên sâu.",
        systemResponse: "Cập nhật quyền hạn và nhóm chat ban tương ứng.",
        icon: "🏷️",
        description: "Tổ chức bộ máy điều hành mạch lạc và chuyên môn hóa cao.",
      },
      {
        targetId: "tour-admin-member-export",
        title: "Xuất Danh Bạ Kỷ Yếu Toàn Hiệp Hội",
        actionGesture: "👆 Chạm nút 'Xuất danh bạ'",
        touchPoint: "Nút xuất dữ liệu kỷ yếu doanh nghiệp",
        instruction: "Bấm để xuất danh bạ đầy đủ phục vụ in ấn ấn phẩm kỷ yếu doanh nhân thường niên.",
        systemResponse: "Xuất file dữ liệu đầy đủ thông tin liên hệ và thương hiệu doanh nghiệp.",
        icon: "📖",
        description: "Ấn phẩm lưu niệm danh giá ghi dấu ấn phát triển của câu lạc bộ.",
      },
    ],
  },
  {
    id: "fees-admin",
    title: "Màn hình Quản Trị Hội Phí & Thu Chi (Ban Tài Chính)",
    subtitle: "Lập đợt thu niên liễm, đối soát VietQR & báo cáo tài chính",
    route: "/fees",
    badge: "CRM Ngoài 3/6",
    iconName: "CreditCard",
    category: "core",
    themeColor: "#059669",
    screenSummary: "Hệ thống quản lý tài chính minh bạch của CLB CEO 1983. Tạo kỳ thu niên liễm, đối soát tự động giao dịch MB Bank qua VietQR và lập báo cáo thu chi công khai.",
    mockupMockTitle: "Quản Trị Hội Phí & Thu Chi",
    mockupElements: [
      { id: "tour-admin-fees-campaign", stepIndex: 1, label: "Tạo Kỳ Thu Niên Liễm Mới", x: 85, y: 15, badgePosition: "left" },
      { id: "tour-admin-fees-status", stepIndex: 2, label: "Theo Dõi Tỷ Lệ Đã Đóng Phí", x: 50, y: 40, badgePosition: "bottom" },
      { id: "tour-admin-fees-reconcile", stepIndex: 3, label: "Đối Soát Tự Động MB Bank", x: 50, y: 65, badgePosition: "top" },
      { id: "tour-admin-fees-report", stepIndex: 4, label: "Xuất Báo Cáo Kế Toán Thu Chi", x: 80, y: 85, badgePosition: "left" },
    ],
    steps: [
      {
        targetId: "tour-admin-fees-campaign",
        title: "Tạo Đợt Thu Hội Phí Thường Niên",
        actionGesture: "👆 Chạm nút '+ Tạo đợt thu'",
        touchPoint: "Nút '+ Tạo kỳ phí mới' ở góc phải màn hình",
        instruction: "Nhập Năm niên liễm (VD: 2026), Mức phí chuẩn (VD: 5.000.000 VNĐ), Hạn nộp và bấm 'Phát hành'.",
        systemResponse: "Tự động tạo hóa đơn INV-2026 cho 200+ hội viên kèm thông báo đẩy.",
        roleNote: "Dành riêng cho Ban Tài Chính và Ban Thư Ký.",
        icon: "💳",
        description: "Quy trình phát hành hóa đơn tự động và đồng bộ thời gian thực.",
      },
      {
        targetId: "tour-admin-fees-status",
        title: "Theo Dõi Tỷ Lệ Đóng Phí Realtime",
        actionGesture: "👁️ Quan sát biểu đồ tỷ lệ thanh toán",
        touchPoint: "Khối thống kê Số tiền đã thu, Số tiền còn nợ và Tỷ lệ hoàn thành %",
        instruction: "Nắm bắt chính xác hội viên nào đã hoàn tất hoặc còn nợ để gửi thông báo nhắc nhở nhẹ nhàng.",
        systemResponse: "Cập nhật dữ liệu tức thì khi có giao dịch VietQR khớp lệnh.",
        icon: "📊",
        description: "Minh bạch tài chính tuyệt đối, chuẩn mực đạo đức kinh doanh doanh nhân.",
      },
      {
        targetId: "tour-admin-fees-reconcile",
        title: "Đối Soát Biến Động Số Dư MB Bank",
        actionGesture: "👆 Chạm nút 'Đối soát ngân hàng'",
        touchPoint: "Mục đối soát giao dịch VietQR tự động",
        instruction: "Hệ thống tự động đọc webhook ngân hàng MB Bank, khớp mã hóa đơn và đóng dấu 'Đã thanh toán'.",
        systemResponse: "Kích hoạt huy hiệu hội viên tích cực ngay sau 1 giây chuyển khoản.",
        icon: "🏦",
        description: "Ứng dụng công nghệ FinTech hiện đại, không cần kế toán kiểm tra thủ công.",
      },
      {
        targetId: "tour-admin-fees-report",
        title: "Xuất Báo Cáo Kế Toán Thu Chi Minh Bạch",
        actionGesture: "👆 Chạm nút 'Báo cáo thu chi'",
        touchPoint: "Nút xuất báo cáo tài chính định kỳ",
        instruction: "Bấm để xuất bảng cân đối thu chi gửi Ban Chấp Hành và báo cáo trước Đại hội toàn thể.",
        systemResponse: "Tải xuống bảng báo cáo tài chính chuẩn kế toán hiệp hội.",
        icon: "📑",
        description: "Đảm bảo tính trung thực và công khai tài chính của câu lạc bộ.",
      },
    ],
  },
  {
    id: "tasks-admin",
    title: "Màn hình Giao Việc & Nhiệm Vụ Điều Hành (Ban Thư Ký)",
    subtitle: "Giao việc liên ban, tiến độ công việc & bảng Kanban điều phối",
    route: "/tasks",
    badge: "CRM Ngoài 4/6",
    iconName: "CheckSquare",
    category: "core",
    themeColor: "#4F46E5",
    screenSummary: "Hệ thống quản lý công việc và giao việc điều hành giữa các ban. Ban Chủ Nhiệm và Ban Thư Ký giao nhiệm vụ, phân bổ ngân sách và đôn đốc tiến độ công tác chuẩn bị sự kiện.",
    mockupMockTitle: "Giao Việc Điều Hành Hiệp Hội",
    mockupElements: [
      { id: "tour-admin-task-create", stepIndex: 1, label: "Nút Giao Việc Mới", x: 85, y: 15, badgePosition: "left" },
      { id: "tour-admin-task-kanban", stepIndex: 2, label: "Bảng Kanban Tiến Độ Công Việc", x: 50, y: 45, badgePosition: "bottom" },
      { id: "tour-admin-task-assignee", stepIndex: 3, label: "Người Chịu Trách Nhiệm & Ban", x: 50, y: 68, badgePosition: "top" },
      { id: "tour-admin-task-deadline", stepIndex: 4, label: "Hạn Chót & Đánh Giá Hoàn Thành", x: 80, y: 85, badgePosition: "left" },
    ],
    steps: [
      {
        targetId: "tour-admin-task-create",
        title: "Khởi Tạo & Giao Nhiệm Vụ Mới",
        actionGesture: "👆 Chạm nút '+ Giao việc mới'",
        touchPoint: "Nút '+ Thêm nhiệm vụ' ở đầu bảng công việc",
        instruction: "Nhập tiêu đề nhiệm vụ (VD: 'Chuẩn bị quà tặng Gala 2026'), chọn Ban phụ trách và người thực hiện.",
        systemResponse: "Mở Modal giao việc và thông báo ngay đến điện thoại người được giao.",
        icon: "➕",
        description: "Phân công nhiệm vụ rõ ràng, đúng người đúng việc trong ban bệ.",
      },
      {
        targetId: "tour-admin-task-kanban",
        title: "Bảng Kanban Trực Quan: Cần Làm - Đang Làm - Hoàn Thành",
        actionGesture: "↔️ Kéo thả thẻ công việc",
        touchPoint: "Các cột trạng thái: Cần làm (To-do), Đang tiến hành (In-progress), Đã hoàn thành (Done)",
        instruction: "Kéo thả thẻ nhiệm vụ sang cột tiếp theo khi hoàn thành từng giai đoạn công việc.",
        systemResponse: "Cập nhật tiến độ dự án và thông báo cho Trưởng ban phụ trách.",
        icon: "📋",
        description: "Phương pháp quản trị Agile hiện đại áp dụng cho công tác điều hành hiệp hội.",
      },
      {
        targetId: "tour-admin-task-assignee",
        title: "Theo Dõi Nhân Sự Chịu Trách Nhiệm",
        actionGesture: "👁️ Quan sát avatar người thực hiện",
        touchPoint: "Thẻ nhiệm vụ có gắn ảnh đại diện và tên ban chuyên trách",
        instruction: "Nhấp vào avatar để nhắn tin trao đổi trực tiếp về khó khăn vướng mắc cần hỗ trợ.",
        systemResponse: "Mở khung chat công việc nội bộ liên quan.",
        icon: "👤",
        description: "Gắn liền trách nhiệm cá nhân với thành công chung của tập thể.",
      },
      {
        targetId: "tour-admin-task-deadline",
        title: "Kiểm Soát Hạn Chót (Deadline) Nghiêm Cẩn",
        actionGesture: "👁️ Kiểm tra thời hạn đếm ngược",
        touchPoint: "Nhãn thời gian hiển thị ngày giờ hết hạn kèm màu sắc cảnh báo",
        instruction: "Các công việc gần đến hạn sẽ chuyển màu vàng cam, quá hạn sẽ cảnh báo màu đỏ khẩn cấp.",
        systemResponse: "Hệ thống tự động gửi thông báo nhắc việc trước 24 giờ.",
        icon: "⏰",
        description: "Đảm bảo mọi khâu chuẩn bị đại hội diễn ra đúng tiến độ đã cam kết.",
      },
    ],
  },
  {
    id: "permissions-admin",
    title: "Màn hình Quản Trị Phân Quyền RBAC (Ban Quản Trị)",
    subtitle: "Ma trận quyền hạn, phân bổ vai trò & ủy quyền nghiệp vụ",
    route: "/permissions",
    badge: "CRM Ngoài 5/6",
    iconName: "Shield",
    category: "core",
    themeColor: "#DC2626",
    screenSummary: "Trung tâm quản trị bảo mật và phân quyền của Hiệp hội CEO 1983. Thiết lập ma trận quyền hạn cho Chủ Tịch, Ban Truyền Thông, Ban Tài Chính, Ban Thư Ký và Lễ Tân Soát Vé.",
    mockupMockTitle: "Quản Trị Phân Quyền RBAC",
    mockupElements: [
      { id: "tour-admin-role-select", stepIndex: 1, label: "Chọn Vai Trò (Admin, Ban Bệ, Hội Viên)", x: 50, y: 18, badgePosition: "bottom" },
      { id: "tour-admin-permission-matrix", stepIndex: 2, label: "Ma Trận Thẩm Quyền Nghiệp Vụ", x: 50, y: 48, badgePosition: "bottom" },
      { id: "tour-admin-checkin-auth", stepIndex: 3, label: "Cấp Quyền Soát Vé Ban Truyền Thông", x: 50, y: 70, badgePosition: "top" },
      { id: "tour-admin-perm-save", stepIndex: 4, label: "Lưu Cấu Hình & Áp Dụng Ngay", x: 80, y: 88, badgePosition: "left" },
    ],
    steps: [
      {
        targetId: "tour-admin-role-select",
        title: "Chọn Vai Trò Trong Bộ Máy Hiệp Hội",
        actionGesture: "👆 Chạm chọn vai trò",
        touchPoint: "Thanh chọn vai trò: Ban Chấp Hành, Trưởng Ban Truyền Thông, Ban Thư Ký, Hội Viên...",
        instruction: "Chọn nhóm đối tượng bạn muốn thiết lập thẩm quyền truy cập hệ thống.",
        systemResponse: "Hiển thị ma trận các quyền hạn tương ứng của vai trò đó.",
        roleNote: "Chỉ tài khoản Super Admin hoặc Chủ Tịch mới có quyền truy cập màn hình này.",
        icon: "🛡️",
        description: "Phân quyền theo vai trò (Role-Based Access Control) chuẩn doanh nghiệp lớn.",
      },
      {
        targetId: "tour-admin-permission-matrix",
        title: "Ma Trận Thẩm Quyền Chi Tiết Từng Phân Hệ",
        actionGesture: "👆 Bật/Tắt các công tắc quyền",
        touchPoint: "Danh sách quyền: Tạo sự kiện, Soát vé, Duyệt hội viên, Xem tài chính, Giao việc...",
        instruction: "Bật công tắc xanh để cấp quyền, hoặc gạt tắt để khóa quyền truy cập của vai trò.",
        systemResponse: "Ghi nhận thay đổi vào bộ nhớ đệm cấu hình bảo mật.",
        icon: "⚙️",
        description: "Kiểm soát an toàn thông tin và bảo vệ các dữ liệu tài chính nhạy cảm.",
      },
      {
        targetId: "tour-admin-checkin-auth",
        title: "Ủy Quyền Soát Vé Cho Nhân Sự Lễ Tân",
        actionGesture: "👆 Bật quyền 'event:checkin'",
        touchPoint: "Mục quyền soát vé sự kiện và quét mã QR tại cổng tiệc",
        instruction: "Cấp quyền này cho nhân sự Ban Truyền Thông để họ mở được camera soát vé trên điện thoại.",
        systemResponse: "Tài khoản được cấp quyền sẽ thấy nút 'Máy Quét Check-in' trong app.",
        icon: "📸",
        description: "Ủy quyền linh hoạt cho ban lễ tân trong ngày diễn ra sự kiện.",
      },
      {
        targetId: "tour-admin-perm-save",
        title: "Lưu Cấu Hình & Đồng Bộ Tức Thì",
        actionGesture: "👆 Chạm nút 'Lưu thay đổi'",
        touchPoint: "Nút lưu cấu hình phân quyền ở góc phải",
        instruction: "Bấm 'Lưu thay đổi' để cập nhật ma trận quyền hạn lên máy chủ toàn hệ thống.",
        systemResponse: "Áp dụng quyền mới ngay lập tức cho các tài khoản đang đăng nhập.",
        icon: "💾",
        description: "Cập nhật chính sách bảo mật tức thời mà không cần khởi động lại máy chủ.",
      },
    ],
  },
  {
    id: "sponsors-admin",
    title: "Màn hình Quản Lý Nhà Tài Trợ & Quyền Lợi (Ban Tài Trợ)",
    subtitle: "Gói Kim Cương, Vàng, Bạc & quyền lợi nhận diện thương hiệu",
    route: "/sponsors",
    badge: "CRM Ngoài 6/6",
    iconName: "Award",
    category: "trade",
    themeColor: "#D97706",
    screenSummary: "Hệ thống quản lý đối tác tài trợ cho các sự kiện và đại hội hiệp hội. Thiết lập gói tài trợ, quản lý logo thương hiệu và giám sát thực hiện quyền lợi tài trợ.",
    mockupMockTitle: "Quản Lý Nhà Tài Trợ Hiệp Hội",
    mockupElements: [
      { id: "tour-admin-sponsor-create", stepIndex: 1, label: "Thêm Đơn Vị Tài Trợ Mới", x: 85, y: 15, badgePosition: "left" },
      { id: "tour-admin-sponsor-packages", stepIndex: 2, label: "Gói Tài Trợ Kim Cương / Vàng / Bạc", x: 50, y: 40, badgePosition: "bottom" },
      { id: "tour-admin-sponsor-logo", stepIndex: 3, label: "Tải Logo & Nhận Diện Thương Hiệu", x: 50, y: 65, badgePosition: "top" },
      { id: "tour-admin-sponsor-report", stepIndex: 4, label: "Báo Cáo Hiệu Quả Hiển Thị Quyền Lợi", x: 80, y: 85, badgePosition: "left" },
    ],
    steps: [
      {
        targetId: "tour-admin-sponsor-create",
        title: "Tiếp Nhận Đơn Vị Đồng Hành Tài Trợ Mới",
        actionGesture: "👆 Chạm nút '+ Thêm nhà tài trợ'",
        touchPoint: "Nút thêm đối tác tài trợ ở thanh công cụ",
        instruction: "Nhập Tên doanh nghiệp tài trợ, Người đại diện, Gói tài trợ và Sự kiện đồng hành.",
        systemResponse: "Mở biểu mẫu đăng ký hồ sơ nhà tài trợ.",
        icon: "➕",
        description: "Ghi nhận đóng góp quý báu của các doanh nghiệp thành viên cho sự phát triển của CLB.",
      },
      {
        targetId: "tour-admin-sponsor-packages",
        title: "Cấu Hình Quyền Lợi Gói Tài Trợ",
        actionGesture: "👆 Chọn gói tài trợ",
        touchPoint: "Các phân hạng gói: Tài trợ Kim Cương, Vàng, Bạc, Đồng và Đồng hành",
        instruction: "Kiểm tra quyền lợi: Phát biểu trên sân khấu, Logo trên backdrop, Bàn tiệc VIP danh dự...",
        systemResponse: "Tự động phân bổ quyền lợi tương ứng với giá trị tài trợ.",
        icon: "💎",
        description: "Đảm bảo thực hiện đầy đủ cam kết quyền lợi với các nhà tài trợ uy tín.",
      },
      {
        targetId: "tour-admin-sponsor-logo",
        title: "Cập Nhật Logo Thương Hiệu Lên Toàn Hệ Thống",
        actionGesture: "👆 Tải tệp logo PNG trong suốt",
        touchPoint: "Khu vực tải lên logo nhà tài trợ",
        instruction: "Tải lên logo chất lượng cao để hệ thống tự động đưa lên banner sự kiện và ứng dụng di động.",
        systemResponse: "Logo xuất hiện ngay trên trang chi tiết sự kiện và màn hình lớn.",
        icon: "🖼️",
        description: "Tôn vinh thương hiệu nhà tài trợ trước cộng đồng 200+ CEO ưu tú.",
      },
      {
        targetId: "tour-admin-sponsor-report",
        title: "Báo Cáo Lượt Tiếp Cận Quyền Lợi Thương Hiệu",
        actionGesture: "👆 Chạm 'Xem báo cáo nghiệm thu'",
        touchPoint: "Nút xuất báo cáo nghiệm thu quyền lợi tài trợ",
        instruction: "Xuất file báo cáo số lượt hiển thị, số lượt quét mã và hình ảnh backdrop thực tế cho nhà tài trợ.",
        systemResponse: "Tải xuống hồ sơ nghiệm thu tài trợ hoàn chỉnh.",
        icon: "📊",
        description: "Thực hiện cam kết nghiệm thu chuyên nghiệp, xây dựng mối quan hệ đồng hành bền vững.",
      },
    ],
  },
];
