/**
 * System-wide Permission & Role Constants
 * CEO 1983 & ViOne Connect CRM
 */

export const SRS_ROLES = {
  ADM: "ADM", // Super Admin / Platform Admin
  BQT: "BQT", // Ban Quản Trị / Ban Thường Trực / Chủ Tịch / Tổng Thư Ký
  BTV: "BTV", // Ban Thành Viên
  BTC: "BTC", // Ban Tài Chính
  BTT: "BTT", // Ban Truyền Thông & Sự Kiện
  HVT: "HVT", // Hội Viên Thường
} as const;

export type SrsRole = (typeof SRS_ROLES)[keyof typeof SRS_ROLES];

export const PERMISSIONS = {
  // Events
  EVENT_VIEW: "event:view",
  EVENT_CREATE: "event:create",
  EVENT_EDIT: "event:edit",
  EVENT_DELETE: "event:delete",
  EVENT_CANCEL: "event:cancel",
  EVENT_CHECKIN_MANAGE: "event:checkin_manage",

  // Sponsors & Packages
  SPONSOR_VIEW: "sponsor:view",
  SPONSOR_CREATE: "sponsor:create",
  SPONSOR_EDIT: "sponsor:edit",
  SPONSOR_DELETE: "sponsor:delete",
  SPONSOR_PACKAGE_MANAGE: "sponsor:package_manage",
  SPONSOR_ASSIGN_EVENT: "sponsor:assign_event",

  // Members
  MEMBER_VIEW: "member:view",
  MEMBER_CREATE: "member:create",
  MEMBER_EDIT: "member:edit",
  MEMBER_DELETE: "member:delete",
  MEMBER_APPROVE: "member:approve",
  MEMBER_RENEW: "member:renew",

  // Finance & Invoices
  FINANCE_VIEW: "finance:view",
  FINANCE_MANAGE: "finance:manage",
  FINANCE_APPROVE: "finance:approve",

  // Media & Communications
  MEDIA_VIEW: "media:view",
  MEDIA_MANAGE: "media:manage",

  // System & Platform Administration
  SYSTEM_MANAGE: "system:manage",
  AUDIT_LOG_VIEW: "system:audit_view",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/**
 * Granular RBAC Role to Permission Mapping
 */
export const ROLE_PERMISSIONS: Record<SrsRole, readonly Permission[]> = {
  ADM: [
    // ADM has all permissions
    PERMISSIONS.EVENT_VIEW,
    PERMISSIONS.EVENT_CREATE,
    PERMISSIONS.EVENT_EDIT,
    PERMISSIONS.EVENT_DELETE,
    PERMISSIONS.EVENT_CANCEL,
    PERMISSIONS.EVENT_CHECKIN_MANAGE,
    PERMISSIONS.SPONSOR_VIEW,
    PERMISSIONS.SPONSOR_CREATE,
    PERMISSIONS.SPONSOR_EDIT,
    PERMISSIONS.SPONSOR_DELETE,
    PERMISSIONS.SPONSOR_PACKAGE_MANAGE,
    PERMISSIONS.SPONSOR_ASSIGN_EVENT,
    PERMISSIONS.MEMBER_VIEW,
    PERMISSIONS.MEMBER_CREATE,
    PERMISSIONS.MEMBER_EDIT,
    PERMISSIONS.MEMBER_DELETE,
    PERMISSIONS.MEMBER_APPROVE,
    PERMISSIONS.MEMBER_RENEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_MANAGE,
    PERMISSIONS.FINANCE_APPROVE,
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.MEDIA_MANAGE,
    PERMISSIONS.SYSTEM_MANAGE,
    PERMISSIONS.AUDIT_LOG_VIEW,
  ],
  BQT: [
    // Ban Quản Trị / Chủ Tịch / Tổng Thư Ký
    PERMISSIONS.EVENT_VIEW,
    PERMISSIONS.EVENT_CREATE,
    PERMISSIONS.EVENT_EDIT,
    PERMISSIONS.EVENT_DELETE,
    PERMISSIONS.EVENT_CANCEL,
    PERMISSIONS.EVENT_CHECKIN_MANAGE,
    PERMISSIONS.SPONSOR_VIEW,
    PERMISSIONS.SPONSOR_CREATE,
    PERMISSIONS.SPONSOR_EDIT,
    PERMISSIONS.SPONSOR_DELETE,
    PERMISSIONS.SPONSOR_PACKAGE_MANAGE,
    PERMISSIONS.SPONSOR_ASSIGN_EVENT,
    PERMISSIONS.MEMBER_VIEW,
    PERMISSIONS.MEMBER_CREATE,
    PERMISSIONS.MEMBER_EDIT,
    PERMISSIONS.MEMBER_DELETE,
    PERMISSIONS.MEMBER_APPROVE,
    PERMISSIONS.MEMBER_RENEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_MANAGE,
    PERMISSIONS.FINANCE_APPROVE,
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.MEDIA_MANAGE,
    PERMISSIONS.SYSTEM_MANAGE,
    PERMISSIONS.AUDIT_LOG_VIEW,
  ],
  BTV: [
    // Ban Thành Viên
    PERMISSIONS.MEMBER_VIEW,
    PERMISSIONS.MEMBER_CREATE,
    PERMISSIONS.MEMBER_EDIT,
    PERMISSIONS.MEMBER_RENEW,
    PERMISSIONS.EVENT_VIEW,
    PERMISSIONS.EVENT_CHECKIN_MANAGE,
    PERMISSIONS.SPONSOR_VIEW,
    PERMISSIONS.MEDIA_VIEW,
  ],
  BTC: [
    // Ban Tài Chính
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_MANAGE,
    PERMISSIONS.FINANCE_APPROVE,
    PERMISSIONS.SPONSOR_VIEW,
    PERMISSIONS.SPONSOR_CREATE,
    PERMISSIONS.SPONSOR_EDIT,
    PERMISSIONS.SPONSOR_PACKAGE_MANAGE,
    PERMISSIONS.MEMBER_VIEW,
    PERMISSIONS.EVENT_VIEW,
  ],
  BTT: [
    // Ban Truyền Thông & Sự Kiện
    PERMISSIONS.EVENT_VIEW,
    PERMISSIONS.EVENT_CREATE,
    PERMISSIONS.EVENT_EDIT,
    PERMISSIONS.EVENT_CHECKIN_MANAGE,
    PERMISSIONS.SPONSOR_VIEW,
    PERMISSIONS.SPONSOR_ASSIGN_EVENT,
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.MEDIA_MANAGE,
    PERMISSIONS.MEMBER_VIEW,
  ],
  HVT: [
    // Hội Viên Thường
    PERMISSIONS.EVENT_VIEW,
    PERMISSIONS.SPONSOR_VIEW,
    PERMISSIONS.MEMBER_VIEW,
    PERMISSIONS.MEDIA_VIEW,
  ],
};
