// scripts/generate_all_160_ucs.js
const fs = require('fs');
const path = require('path');

// 1. Phân hệ 1: Cổng Thông Tin Công Khai & Tiếp Nhận Báo Giá (15 UCs)
const pubData = [
  ['UC-VN-PUB-01', 'Xem Hero Section & Trải Nghiệm Hoạt Ảnh 4.8s Pop-up Keyframe', 'Khách vãng lai, Doanh nhân', 'Truy cập https://vione.ai', '1. Tải trang chủ phong cách Hoàng gia Doanh nhân.\n2. Kích hoạt hoạt ảnh 4.8s: Hình ảnh doanh nhân pop-up phía trước smartphone.\n3. Xem các chỉ số hiệu suất: 98.4% tin cậy, 10x tốc độ, AI bot tự động.\n4. Đọc thông điệp Hệ sinh thái số hóa toàn diện 5.0.', 'Fallback hiển thị đồ họa tĩnh nếu trình duyệt tắt animation.', 'Ghi nhận 01 lượt Pageview ẩn danh.', '01_landing_hero.png', 'Giao diện Hero Section Landing Web với Hoạt ảnh Pop-up 4.8s Doanh nhân & Smartphone 3D'],
  ['UC-VN-PUB-02', 'Khám Phá Mô Đun Liên Kết & Kiến Trúc Hợp Nhất 4 Trụ Cột', 'Khách vãng lai, Giám đốc điều hành', 'Cuộn xuống mục Mô Đun', '1. Xem 4 khối phân hệ: CRM, Work, Finance, HRM.\n2. Rê chuột xem viền vàng hoàng gia và mô tả tính năng chuyên sâu.\n3. Bấm xem sơ đồ dòng chảy dữ liệu đồng nhất giữa 4 phân hệ.', 'Chuyển tab bằng phím mũi tên trái/phải.', 'Nắm rõ kiến trúc dữ liệu tập trung, xóa bỏ phân mảnh.', '02_landing_cinematic.png', 'Sơ đồ Kiến trúc Hợp nhất 4 Phân hệ Cốt lõi: CRM, Work, Finance và HRM'],
  ['UC-VN-PUB-03', 'Trải Nghiệm Bộ Máy Tự Động Hóa Quy Trình AI Workflow Copilot', 'Chuyên viên Vận hành, Giám đốc COO', 'Cuộn tới mục AI Workflow', '1. Xem mô hình trực quan Trigger -> AI Analysis -> Multi-channel Action.\n2. Thử nghiệm kịch bản mẫu tiếp nhận Lead và gửi báo giá tự động trong 60s.\n3. Quan sát mô phỏng thông báo đồng thời đến CRM và mobile app.', 'Chọn kịch bản khác: Duyệt chi tài chính hoặc Cảnh báo quá hạn.', 'Nắm rõ năng lực cắt giảm 40% chi phí vận hành.', 'workflow-automation.png', 'Mô hình Trực quan Hóa Bộ Máy Tự Động Hóa Quy Trình Đa Kênh AI Workflow Copilot'],
  ['UC-VN-PUB-04', 'Xem Trung Tâm Giám Sát Vận Hành & Đo Lường SLA Thời Gian Thực', 'Ban Giám Đốc, Giám đốc CFO', 'Quan sát khu vực Giám sát', '1. Xem mô phỏng màn hình giám sát máy tính chuẩn doanh nghiệp.\n2. Quan sát đồ thị đo SLA < 150ms và uptime máy chủ 99.98%.\n3. Đọc số liệu doanh thu thực, công nợ và tiến độ KPI.', 'Phóng to ảnh xem chi tiết đồ thị.', 'Yên tâm về năng lực kiểm soát dữ liệu 24/7.', 'operational-dashboard.png', 'Trung Tâm Giám Sát Vận Hành Tổng Thể & Đo Lường Chỉ Số KPI Doanh Nghiệp Thời Gian Thực'],
  ['UC-VN-PUB-05', 'Khám Phá Quy Trình 3 Bước Thiết Lập Tự Động Siêu Tốc Trong 5 Phút', 'Chủ Doanh Nghiệp, Quản trị viên', 'Xem mục 3 Bước Thiết lập', '1. Xem Bước 01 Trigger: Kết nối nguồn kích hoạt (Web form, Fanpage, Zalo).\n2. Xem Bước 02 Actions: Định cấu hình điều kiện tự động kéo thả không code.\n3. Xem Bước 03 Monitor: Kích hoạt giám sát và nhận báo cáo định kỳ.', 'Xem tài liệu hướng dẫn triển khai nhanh.', 'Xóa bỏ rào cản sợ phần mềm phức tạp lâu năm.', 'business-laptop.png', 'Quy Trình 3 Bước Thiết Lập Vận Hành Siêu Tốc Trong 5 Phút'],
  ['UC-VN-PUB-06', 'Đánh Giá 4 Trụ Cột Giá Trị Cốt Lõi & Tiêu Chuẩn Bảo Mật AES-256', 'Giám đốc CISO, Chuyên gia pháp chế', 'Xem mục Giá Trị Doanh Nghiệp', '1. Đọc 4 trụ cột: Giảm chi phí, Data-driven, Trải nghiệm, Bảo mật.\n2. Kiểm tra chứng chỉ mã hóa cơ sở dữ liệu AES-256, TLS 1.3.\n3. Xem cam kết SLA bồi hoàn nếu gián đoạn dịch vụ.', 'Yêu cầu gửi Bản cáo bạch An toàn thông tin qua email.', 'Xác thực độ tin cậy và pháp lý của ViOne.', '01_crm_login_blue_white.png', 'Trụ Cột Giá Trị Cốt Lõi & Tiêu Chuẩn An Toàn Bảo Mật Đa Tầng Cấp Doanh Nghiệp'],
  ['UC-VN-PUB-07', 'Khám Phá Mô Hình Giải Pháp Phù Hợp Đa Dạng Mô Hình Ngành Nghề', 'Chủ doanh nghiệp các ngành', 'Xem mục Giải Pháp Ngành Nghề', '1. Xem giải pháp ngành Thương mại & Dịch vụ: Hợp đồng, Kanban việc.\n2. Xem giải pháp ngành Chuỗi & Bán lẻ: Đối soát doanh thu, VietQR.\n3. Xem giải pháp ngành Sản xuất & Phân phối: Đại lý B2B, Catalog.', 'Nhấp từng tab ngành xem chi tiết tính năng.', 'Hình dung trọn vẹn bài toán của công ty mình.', 'business-laptop.png', 'Giải Pháp Số Hóa Vận Hành May Đo Theo Đa Dạng Nhóm Ngành Nghề'],
  ['UC-VN-PUB-08', 'Tra Cứu Đánh Giá Của Khách Hàng Lãnh Đạo Tiêu Biểu (Testimonials)', 'Khách hàng tiềm năng', 'Xem phần Testimonials', '1. Xem ảnh chân dung và nhận xét của TGĐ Nguyễn Minh Đăng.\n2. Đọc kết quả: Quản lý 5 chi nhánh trực tiếp trên smartphone.\n3. Quan sát logo các tập đoàn, hiệp hội tiêu biểu.', 'Vuốt xem qua lại giữa các câu chuyện thành công.', 'Gia tăng niềm tin và động lực đăng ký tư vấn.', 'avatar-ceo.png', 'Chia Sẻ Đánh Giá Thực Tế Từ Lãnh Đạo Doanh Nghiệp Đang Vận Hành Hệ Thống ViOne'],
  ['UC-VN-PUB-09', 'Tham Khảo Cấu Trúc Bảng Giá Dịch Vụ Tùy Biến 3 Gói Giải Pháp', 'Đại diện bộ phận thu mua', 'Xem mục Bảng Giá Dịch Vụ', '1. Xem 3 gói: Starter (Khởi tạo), Growth (Tăng trưởng), Enterprise (Doanh nghiệp lớn).\n2. Đọc chi tiết danh mục tính năng mở khóa theo quy mô nhân sự.\n3. Ghi nhận chính sách không hiển thị giá cứng, cam kết tư vấn may đo.\n4. Bấm nút CTA Yêu cầu báo giá trên gói phù hợp.', 'Bật tắt bảng so sánh đối chiếu tính năng giữa các gói.', 'Xác định gói giải pháp mục tiêu.', 'crm_dash_view_06.png', 'Cấu Trúc 3 Gói Giải Pháp Số Hóa Doanh Nghiệp & Chính Sách Báo Giá May Đo'],
  ['UC-VN-PUB-10', 'Mở & Điền Form Yêu Cầu Báo Giá & Tư Vấn 1-1 Chuyên Sâu', 'Đại diện doanh nghiệp', 'Bấm nút Yêu cầu báo giá', '1. Mở Modal Hoàng gia Vàng Đồng sang trọng.\n2. Nhập: Họ tên, Số điện thoại, Email, Tên công ty, Quy mô nhân sự, Nhu cầu.\n3. Bấm Gửi yêu cầu báo giá.\n4. Hệ thống validate và lưu vào bảng vione_quote_leads.\n5. Hiển thị thông báo cảm ơn và cam kết liên hệ trong 15 phút.', 'Báo lỗi đỏ nếu thiếu số điện thoại hoặc email sai định dạng.', 'Lead được ghi nhận và gửi thông báo cho đội ngũ tư vấn.', 'live_02_member_registration_form_filled.png', 'Cửa Sổ Modal Tiếp Nhận Yêu Cầu Báo Giá May Đo & Hồ Sơ Tư Vấn 1-1'],
  ['UC-VN-PUB-11', 'Tra Cứu & Tìm Kiếm Câu Hỏi Thường Gặp (Interactive FAQ Accordion)', 'Khách vãng lai', 'Xem phần FAQ', '1. Xem danh sách câu hỏi: Thời gian triển khai, Tích hợp kế toán cũ, Bảo mật.\n2. Bấm vào tiêu đề câu hỏi để mở rộng nội dung giải đáp.\n3. Đọc chính sách sao lưu và xuất dữ liệu dự phòng.', 'Tìm kiếm từ khóa câu hỏi trong thanh tìm kiếm nhanh.', 'Giải tỏa mọi băn khoăn trước khi đăng ký.', 'live_07_crm_member_detail_drawer.png', 'Khu Vực Hỏi Đáp Thường Gặp FAQ Với Hiệu Ứng Accordion Mở Rộng Linh Hoạt'],
  ['UC-VN-PUB-12', 'Tải Xuống Hồ Sơ Năng Lực Doanh Nghiệp (Company Profile PDF)', 'Thư ký ban giám đốc, Thu mua', 'Bấm nút Tải Hồ Sơ Năng Lực', '1. Nhấp liên kết tải tài liệu.\n2. Nhập nhanh email công ty nhận tài liệu.\n3. Tải xuống file ViOne_Platform_Company_Profile_2026.pdf chất lượng cao.', 'Gửi link tải dự phòng qua hòm thư điện tử nếu lỗi mạng.', 'Có tài liệu PDF chuyên nghiệp báo cáo cấp trên.', '10_app_user_guide_pdf_viewer.png', 'Giao Diện Trình Đọc & Tải Xuống Hồ Sơ Năng Lực PDF Chuẩn Doanh Nghiệp'],
  ['UC-VN-PUB-13', 'Chuyển Đổi Giao Diện Đa Ngôn Ngữ (Tiếng Việt / English)', 'Đối tác quốc tế, Doanh nghiệp FDI', 'Bấm biểu tượng ngôn ngữ Header', '1. Chọn ngôn ngữ Tiếng Anh (EN).\n2. Toàn bộ nội dung, nút bấm và form tự động đổi sang tiếng Anh.\n3. Lưu lựa chọn ngôn ngữ vào LocalStorage của trình duyệt.', 'Hệ thống tự nhận diện ngôn ngữ máy trạm khi vào lần đầu.', 'Phục vụ khách hàng toàn cầu và đối tác FDI.', '01_landing_hero.png', 'Bộ Chuyển Đổi Ngôn Ngữ Song Ngữ Anh - Việt Trên Thanh Điều Hướng Header'],
  ['UC-VN-PUB-14', 'Đăng Ký Nhận Bản Tin Xu Hướng Quản Trị & Chuyển Đổi Số', 'Chuyên viên quản lý, Doanh nhân', 'Xem khu vực Footer', '1. Nhập email vào ô Nhận bản tin quản trị.\n2. Bấm nút Đăng Ký.\n3. Hệ thống kiểm tra và lưu vào danh bạ gửi tin tự động.\n4. Hiển thị thông báo cảm ơn và gửi tặng Ebook Quản trị.', 'Báo thông báo nếu email đã tồn tại trong danh bạ.', 'Dữ liệu được lưu trữ an toàn cho Inbound Marketing.', '05_email_credentials_sent.png', 'Xác Nhận Đăng Ký Bản Tin Số Hóa Doanh Nghiệp & Tự Động Gửi Email Chào Mừng'],
  ['UC-VN-PUB-15', 'Tra Cứu Thông Tin Pháp Lý, Điều Khoản Dịch Vụ & Chính Sách Bảo Mật', 'Chuyên viên pháp chế doanh nghiệp', 'Bấm liên kết Điều khoản tại Footer', '1. Mở trang pháp lý chính thức.\n2. Xem quy định: Khách hàng sở hữu 100% dữ liệu, không chia sẻ bên thứ ba.\n3. Xem quy trình tiêu hủy dữ liệu khi thanh lý hợp đồng.', 'Hỗ trợ in ấn văn bản pháp lý với định dạng in sạch.', 'Doanh nghiệp an tâm tuyệt đối về mặt pháp lý.', '02_crm_members_roles_permission.png', 'Trang Điều Khoản Dịch Vụ & Chính Sách Bảo Mật Dữ Liệu Doanh Nghiệp Chuẩn Mực']
];

// Helper to push array
const allUCs = [];

pubData.forEach(d => {
  allUCs.push({
    id: d[0],
    category: 'Cổng Thông Tin Công Khai & Tiếp Nhận Báo Giá',
    name: d[1],
    actor: d[2],
    preConditions: d[3],
    mainFlow: d[4],
    alternativeFlow: d[5],
    postConditions: d[6],
    imageFile: d[7],
    imageCaption: d[8]
  });
});

console.log('Phân hệ 1 xong:', allUCs.length);

module.exports = { allUCs };
