  {
    id: "M1983-001",
    code: "M1983-001",
    name: "Lê Thị Dung",
    contact: "Lê Thị Dung",
    email: "ledung22183@gmail.com",
    phone: "0988870888",
    type: "company",
    level: "vip",
    industry: "Tư vấn, đào tạo doanh nghiệp",
    region: "region.north",
    status: "active",
    joinedAt: "2022-08-18T00:00:00Z",
    feeYear: 2026,
    feePaid: true,
    address: "R2B, royal city, 72 A Nguyễn Trãi, Thượng Đình, Thanh Xuân, HN",
    website: "https://ceo1983.vn",
    about: "Công ty CP Đào tạo và phát triển nhân lực DGroup · Viện trưởng, Tổng giám đốc · Tư vấn, đào tạo doanh nghiệp",
    department: "Ban Quản Trị",
    executiveRole: "Chủ tịch CLB",
  },
  {
    id: "M1983-002",
    code: "M1983-002",
    name: "Hoàng Thanh Tuấn",
    contact: "Hoàng Thanh Tuấn",
    email: "tuanht.vb@gmail.com",
    phone: "0983988999",
    type: "company",
    level: "vip",
    industry: "Phẫu thuật thẩm mỹ, Nha khoa thẩm mỹ và Da liễu thẩm mỹ",
    region: "region.north",
    status: "active",
    joinedAt: "2022-10-20T00:00:00Z",
    feeYear: 2026,
    feePaid: true,
    address: "Hà Nội (02), Hạ Long, Hải Phòng",
    website: "https://ceo1983.vn",
    about: "Thẩm mỹ Hoàng Tuấn · Chủ tịch Hội đồng cố vấn · Phẫu thuật thẩm mỹ, Nha khoa thẩm mỹ và Da liễu thẩm mỹ",
    department: "Ban Quản Trị",
    executiveRole: "Phó Chủ tịch CLB",
  },
  {
    id: "M1983-003",
    code: "M1983-003",
    name: "Nguyễn Thanh Tuấn",
    contact: "Nguyễn Thanh Tuấn",
    email: "tuannt@saokim.com.vn",
    phone: "0964699499",
    type: "company",
    level: "vip",
    industry: "Tư vấn chiến lược, thiết kế thương hiệu và truyền thông",
    region: "region.north",
    status: "active",
    joinedAt: "2022-08-18T00:00:00Z",
    feeYear: 2026,
    feePaid: true,
    address: "35 Lê Văn Thiêm, Thanh Xuân, Hà Nội",
    website: "https://ceo1983.vn",
    about: "Công ty CP tư vấn thương hiệu Sao Kim · Chủ tịch HĐQT · Tư vấn chiến lược, thiết kế thương hiệu và truyền thông",
    department: "Ban Quản Trị",
    executiveRole: "Phó Chủ tịch CLB",
  },
  {
    id: "M1983-004",
    code: "M1983-004",
    name: "Nguyễn Trung Kiên",
    contact: "Nguyễn Trung Kiên",
    email: "ceo.acmholdings@gmail.com",
    phone: "0767313314",
    type: "company",
    level: "vip",
    industry: "Quản lý quỹ đầu tư, đầu tư doanh nghiệp",
    region: "region.north",
    status: "active",
    joinedAt: "2022-08-18T00:00:00Z",
    feeYear: 2026,
    feePaid: true,
    address: "Số 11D, ô A10, KĐT Nam Trung Yên, Quận Cầu Giấy, Hà Nội đổi về 49 Trung Kính,  Yên Hòa, Hà Nội",
    website: "https://ceo1983.vn",
    about: "Công ty cổ phần ACM HOLDINGS/ Viện chiến lược công nghệ và đổi mới sáng tạo (STI) · Viện trưởng · Quản lý quỹ đầu tư, đầu tư doanh nghiệp",
    department: "Ban Quản Trị",
    executiveRole: "Phó Chủ tịch CLB",
  },
  {
    id: "M1983-005",
    code: "M1983-005",
    name: "Đỗ Minh Thành",
    contact: "Đỗ Minh Thành",
    email: "thanh.dm@valis.vn",
    phone: "0948396888",
    type: "company",
    level: "vip",
    industry: "Nhập khẩu và phân phối các sản phẩm âm thanh biểu diễn chuyên nghiệp, âm thanh karaoke, hội trường, bar,cafe, nhà hàng, khách sạn, spa, công viên…",
    region: "region.north",
    status: "active",
    joinedAt: "2023-03-31T00:00:00Z",
    feeYear: 2026,
    feePaid: true,
    address: "Khu hacinco nguyễn xiển
   Showroom:122 trần duy hưng",
    website: "https://ceo1983.vn",
    about: "Công ty Cổ phần Valis Corporation · CEO · Nhập khẩu và phân phối các sản phẩm âm thanh biểu diễn chuyên nghiệp, âm thanh karaoke, hội trường, bar,cafe, nhà hàng, khách sạn, spa, công viên…",
    department: "Ban Quản Trị",
    executiveRole: "Phó Chủ tịch CLB",
  },
  {
    id: "M1983-006",
    code: "M1983-006",
    name: "Nguyễn Đình Toản",
    contact: "Nguyễn Đình Toản",
    email: "toannd2910@gmail.com",
    phone: "0989310558",
    type: "company",
    level: "vip",
    industry: "PTDA, Đầu tư, phân phối BĐS",
    region: "region.north",
    status: "active",
    joinedAt: "2022-08-18T00:00:00Z",
    feeYear: 2026,
    feePaid: true,
    address: "Số 11, ngõ 82 Dịch Vọng Hậu, Cầu Giấy, Hà nội",
    website: "https://ceo1983.vn",
    about: "Công ty Cổ phần Địa ốc Tân Hưng Gia · Chủ tịch HĐQT · PTDA, Đầu tư, phân phối BĐS",
    department: "Ban Thư Ký & Điều Phối",
    executiveRole: "Trưởng Ban",
  },
  {
    id: "M1983-007",
    code: "M1983-007",
    name: "Phùng Quyết Thanh",
    contact: "Phùng Quyết Thanh",
    email: "thanh.pq@quyettienco.com",
    phone: "0987879689",
    type: "company",
    level: "vip",
    industry: "Kinh doanh thiết bị điện và thiết bị chiếu sáng",
    region: "region.north",
    status: "active",
    joinedAt: "2022-11-11T00:00:00Z",
    feeYear: 2026,
    feePaid: true,
    address: "Số 35, ngõ 68, Đường Nguyễn Văn Linh, Thạch Bàn, Long Biên, Hà Nội",
    website: "https://ceo1983.vn",
    about: "Công ty TNHH Thiết bị và Công nghệ Quyết Tiến · Giám Đốc · Kinh doanh thiết bị điện và thiết bị chiếu sáng",
    department: "Ban Xúc Tiến Thương Mại & Đầu Tư B2B",
    executiveRole: "Phó Ban",
  },
  {
    id: "M1983-008",
    code: "M1983-008",
    name: "Nguyễn Thế Duẩn",
    contact: "Nguyễn Thế Duẩn",
    email: "theduan.pvn@gmail.com",
    phone: "0984247726",
    type: "company",
    level: "vip",
    industry: "In ấn, thiết kế tem nhãn bao bì",
    region: "region.north",
    status: "active",
    joinedAt: "2022-11-08T00:00:00Z",
    feeYear: 2026,
    feePaid: true,
    address: "Khu công nghiệp Quang Minh",
    website: "https://ceo1983.vn",
    about: "Công ty cổ phần PVN · Giám Đốc · In ấn, thiết kế tem nhãn bao bì",
    department: "Ban Quản Trị",
    executiveRole: "Phó Chủ tịch CLB",
  },
  {
    id: "M1983-009",
    code: "M1983-009",
    name: "Nguyễn Thị Hồng Trang",
    contact: "Nguyễn Thị Hồng Trang",
    email: "nguyentrang021083@gmail.com",
    phone: "0983126918",
    type: "company",
    level: "vip",
    industry: "Cung cấp máy móc ngành in- dán tem nhãn decan, label, bao bì",
    region: "region.north",
    status: "active",
    joinedAt: "2022-11-03T00:00:00Z",
    feeYear: 2026,
    feePaid: true,
    address: "Long Biên",
    website: "https://ceo1983.vn",
    about: "Công ty TNHH sản xuất thương mại và dịch vụ Việt An Phát · Giám Đốc · Cung cấp máy móc ngành in- dán tem nhãn decan, label, bao bì",
    department: "Ban Phát Triển Hội Viên & Thẩm Định",
    executiveRole: "Ủy Viên BCH",
  },
  {
    id: "M1983-010",
    code: "M1983-010",
    name: "Trần Ánh Phương",
    contact: "Trần Ánh Phương",
    email: "phuong.trananh83@gmail.com",
    phone: "0903299616",
    type: "company",
    level: "vip",
    industry: "Nhập khẩu và phân phối đồ Hàn",
    region: "region.north",
    status: "active",
    joinedAt: "2022-11-30T00:00:00Z",
    feeYear: 2026,
    feePaid: true,
    address: "tòa nhà MD Complex, số 68 phố Nguyễn Cơ Thạch - Phường Cầu Diễn - Quận Nam Từ Liêm - Hà Nội.",
    website: "https://ceo1983.vn",
    about: "Công ty TNHH T’imex · CEO · Nhập khẩu và phân phối đồ Hàn",
    department: "Ban Truyền Thông & Sự Kiện",
    executiveRole: "Thành Viên",
  },
  {
    id: "M1983-011",
    code: "M1983-011",
    name: "Hoàng Văn Nam",
    contact: "Hoàng Văn Nam",
    email: "kevin.nam@globalcom.vn",
    phone: "0988311882",
    type: "company",
    level: "vip",
    industry: "Logistic",
    region: "region.north",
    status: "active",
    joinedAt: "2023-03-31T00:00:00Z",
    feeYear: 2026,
    feePaid: true,
    address: "Tầng 7, Tòa nhà Văn phòng Lucky, số 81 Trần Thái Tông, phường Dịch Vọng, Quận Cầu Giấy, Hà Nội",
    website: "https://ceo1983.vn",
    about: "Công Ty TNHH Kho Vận Globalcom · Giám Đốc · Logistic",
    department: "Ban Tài Chính & Pháp Chế",
    executiveRole: "Trưởng Ban",
  },
  {
    id: "M1983-012",
    code: "M1983-012",
    name: "Nguyễn Vân Hương",
    contact: "Nguyễn Vân Hương",
    email: "vanhuongplvn@gmail.com",
    phone: "0904157755",
    type: "company",
    level: "vip",
    industry: "Báo Pháp luật Việt Nam",
    region: "region.north",
    status: "active",
    joinedAt: "2023-03-31T00:00:00Z",
    feeYear: 2026,
    feePaid: true,
    address: "Số 42 ngõ 29 Nguyễn Chí Thanh, Hà Nội",
    website: "https://ceo1983.vn",
    about: "Phó Ban Doanh nhân & Pháp luật Truyền thông, hỗ trợ pháp lý cho doanh nghiệp - Báo Pháp luật Việt Nam · CEO · Báo Pháp luật Việt Nam",
    department: "Ban Đào Tạo & Chuyển Đổi Số",
    executiveRole: "Phó Ban",
  },
  {
    id: "M1983-013",
    code: "M1983-013",
    name: "Cao Văn Mạnh",
    contact: "Cao Văn Mạnh",
    email: "master@hoaduong.vn",
    phone: "0982848884",
    type: "company",
    level: "vip",
    industry: "Các chương trình giải trí, sản xuất videos viral, quản lý celeb, tổ chức sự kiện, xây dựng các nền tảng MXH",
    region: "region.north",
    status: "active",
    joinedAt: "2023-03-02T00:00:00Z",
    feeYear: 2026,
    feePaid: true,
    address: "Mỹ Đình, Hà Nội",
    website: "https://ceo1983.vn",
    about: "Hoa Dương Entertainment(Công ty CP Nghệ thuật Giải trí Hoa Dương) · CEO · Các chương trình giải trí, sản xuất videos viral, quản lý celeb, tổ chức sự kiện, xây dựng các nền tảng MXH",
    department: "Ban Thư Ký & Điều Phối",
    executiveRole: "Ủy Viên BCH",
  },
  {
    id: "M1983-014",
    code: "M1983-014",
    name: "Hoàng Thị Ngọc Ánh",
    contact: "Hoàng Thị Ngọc Ánh",
    email: "hoanganh@avtravel.com.vn",
    phone: "0941272222",
    type: "company",
    level: "vip",
    industry: "Du lịch và vé máy bay từ năm 2007
   Viện Thẩm mỹ gồm 13 chi nhánh trên toàn quốc từ năm 2018",
    region: "region.north",
    status: "active",
    joinedAt: "2023-03-03T00:00:00Z",
    feeYear: 2026,
    feePaid: true,
    address: "Số 106/2 - A2 Lạc Chính, Phường Trúc Bạch, Quận Ba Đình",
    website: "https://ceo1983.vn",
    about: "Công ty cổ phần thương mại AV · CEO · Du lịch và vé máy bay từ năm 2007
   Viện Thẩm mỹ gồm 13 chi nhánh trên toàn quốc từ năm 2018",
    department: "Ban Xúc Tiến Thương Mại & Đầu Tư B2B",
    executiveRole: "Thành Viên",
  },
  {
    id: "M1983-015",
    code: "M1983-015",
    name: "Triệu Văn Ba",
    contact: "Triệu Văn Ba",
    email: "congtycophanvietphu@gmail.com",
    phone: "0973256686",
    type: "company",
    level: "vip",
    industry: "Xây dựng các công trình dân dụng, hạ tầng kỹ thuật, giao thông thủy lợi, sản xuất gia công cơ khí, nhôm kính, biển quảng cáo",
    region: "region.north",
    status: "active",
    joinedAt: "2023-05-09T00:00:00Z",
    feeYear: 2026,
    feePaid: true,
    address: "Thôn Ngọc Trì, Xã Kim Hoa, Huyện Mê Linh, Thành phố Hà Nội",
    website: "https://ceo1983.vn",
    about: "Công ty Cổ phần Đầu tư phát triển xây dựng Việt Phú · Chủ tịch HĐQT · Xây dựng các công trình dân dụng, hạ tầng kỹ thuật, giao thông thủy lợi, sản xuất gia công cơ khí, nhôm kính, biển quảng cáo",
    department: "Ban Quản Trị",
    executiveRole: "Phó Chủ tịch CLB",
  },
  {
    id: "M1983-016",
    code: "M1983-016",
    name: "Dương Thị Huệ",
    contact: "Dương Thị Huệ",
    email: "huedohoa@gmail.com",
    phone: "0983971783",
    type: "company",
    level: "vip",
    industry: "Sự kiện - Tour du lịch.",
    region: "region.north",
    status: "active",
    joinedAt: "2023-05-23T00:00:00Z",
    feeYear: 2026,
    feePaid: true,
    address: "21 Lê Văn Lương",
    website: "https://ceo1983.vn",
    about: "Công ty Cổ phần Đại Khánh Holding · Giám Đốc · Sự kiện - Tour du lịch.",
    department: "Ban Phát Triển Hội Viên & Thẩm Định",
    executiveRole: "Trưởng Ban",
  },
  {
    id: "M1983-017",
    code: "M1983-017",
    name: "Nguyễn Thị Khuyên",
    contact: "Nguyễn Thị Khuyên",
    email: "nasakivn@gmail.com",
    phone: "0982695550",
    type: "company",
    level: "vip",
    industry: "Sản xuất ngói màu không nung, tấm ốp tường",
    region: "region.north",
    status: "active",
    joinedAt: "2023-03-31T00:00:00Z",
    feeYear: 2026,
    feePaid: true,
    address: "Khu công nghiệp phía Nam TP yên bái tỉnh yên bái",
    website: "https://ceo1983.vn",
    about: "Công ty TNHH NASAKI Việt Nam · Giám Đốc · Sản xuất ngói màu không nung, tấm ốp tường",
    department: "Ban Truyền Thông & Sự Kiện",
    executiveRole: "Phó Ban",
  },
  {
    id: "M1983-018",
    code: "M1983-018",
    name: "Nguyễn Anh Tuấn",
    contact: "Nguyễn Anh Tuấn",
    email: "tuan.nguyen@haseca.com",
    phone: "0915062564",
    type: "company",
    level: "vip",
    industry: "Thực phẩm",
    region: "region.north",
    status: "active",
    joinedAt: "2023-07-07T00:00:00Z",
    feeYear: 2026,
    feePaid: true,
    address: "số 69, đường 37 KDT Vạn Phúc, Thủ Đức, TP HCM",
    website: "https://ceo1983.vn",
    about: "Công ty Cổ phần Quốc tế Haseca mekong / Công ty Cổ phần Quốc tế Alpha food · Giám Đốc · Thực phẩm",
    department: "Ban Quản Trị",
    executiveRole: "Phó Chủ tịch CLB",
  },
  {
    id: "M1983-019",
    code: "M1983-019",
    name: "Phạm Văn Hùng",
    contact: "Phạm Văn Hùng",
    email: "hungpham@hoangsaviet.com",
    phone: "0942222075",
    type: "company",
    level: "vip",
    industry: "Xây dựng nhà lắp ghép. Thang máy. Ẩm thực F&B. Nhà Hàng Chay. Âm Thanh Ánh Sáng. Màn hình LED và Tổ Chức Sự Kiện",
    region: "region.north",
    status: "active",
    joinedAt: "2023-08-03T00:00:00Z",
    feeYear: 2026,
    feePaid: true,
    address: "184/20A Lê Đình Cẩn, Tân Tạo, Bình Tân, HCM",
    website: "https://ceo1983.vn",
    about: "Công ty CP Đầu tư và Phát triển Hoàng Sa Việt · CEO · Xây dựng nhà lắp ghép. Thang máy. Ẩm thực F&B. Nhà Hàng Chay. Âm Thanh Ánh Sáng. Màn hình LED và Tổ Chức Sự Kiện",
    department: "Ban Tài Chính & Pháp Chế",
    executiveRole: "Ủy Viên BCH",
  },
  {
    id: "M1983-020",
    code: "M1983-020",
    name: "Nguyễn Thị Phượng (Trang Nguyễn)",
    contact: "Nguyễn Thị Phượng (Trang Nguyễn)",
    email: "trangnguyentrangh84@gmail.com",
    phone: "0907117118",
    type: "company",
    level: "vip",
    industry: "F&B",
    region: "region.north",
    status: "active",
    joinedAt: "2023-08-04T00:00:00Z",
    feeYear: 2026,
    feePaid: true,
    address: "122 đường số 7, p Tân kiểng. Q7. TP HCM",
    website: "https://ceo1983.vn",
    about: "Công ty TNHH TMDV Nhà hàng SOS · Giám Đốc · F&B",
    department: "Ban Đào Tạo & Chuyển Đổi Số",
    executiveRole: "Thành Viên",
  },
  {
    id: "M1983-021",
    code: "M1983-021",
    name: "Nguyễn Phi Hồng Nguyên",
    contact: "Nguyễn Phi Hồng Nguyên",
    email: "admin@vietpromotion.vn",
    phone: "0908898475",
    type: "company",
    level: "vip",
    industry: "Lữ Hành – Dịch Vụ - Sự Kiện – Xúc Tiến Thương Mại",
    region: "region.north",
    status: "active",
    joinedAt: "2024-03-01T00:00:00Z",
    feeYear: 2026,
    feePaid: true,
    address: "9/8 Hương Điền – Phường Phước Hải – Thành Phố Nha Trang. Tỉnh Khánh Hòa",
    website: "https://ceo1983.vn",
    about: "Công Ty TNHH Dịch Vụ Và Du Lịch Việt Promotion · Giám Đốc · Lữ Hành – Dịch Vụ - Sự Kiện – Xúc Tiến Thương Mại",
    department: "Ban Thư Ký & Điều Phối",
    executiveRole: "Trưởng Ban",
  },
  {
    id: "M1983-022",
    code: "M1983-022",
    name: "Đặng Văn Giang",
    contact: "Đặng Văn Giang",
    email: "hoanggiangpt44b@gmail.com",
    phone: "0974788686",
    type: "company",
    level: "vip",
    industry: "Nước cốt nhàu",
    region: "region.north",
    status: "active",
    joinedAt: "2024-07-01T00:00:00Z",
    feeYear: 2026,
    feePaid: true,
    address: "số 3 Lê Cao Lãng, Phường Phú Thạnh, Quận Tân Phú, HCM.",
    website: "https://ceo1983.vn",
    about: "Công ty TNHH Nonifarm · Giám Đốc · Nước cốt nhàu",
    department: "Ban Xúc Tiến Thương Mại & Đầu Tư B2B",
    executiveRole: "Phó Ban",
  },
  {
    id: "M1983-023",
    code: "M1983-023",
    name: "Trịnh Quang Thái",
    contact: "Trịnh Quang Thái",
    email: "thaitq@tcsoft.vn",
    phone: "0912841157",
    type: "company",
    level: "vip",
    industry: "Phần mềm quản lý; chuyển đổi số",
    region: "region.north",
    status: "active",
    joinedAt: "2025-01-09T00:00:00Z",
    feeYear: 2026,
    feePaid: true,
    address: "Số 16/158 Phố Đại Từ, phường Đại Kim, quận Hoàng Mai, TP HN",
    website: "https://ceo1983.vn",
    about: "Công ty TNHH Thương mại và Phát triển công nghệ phần mềm TCSOFT · Giám Đốc · Phần mềm quản lý; chuyển đổi số",
    department: "Ban Phát Triển Hội Viên & Thẩm Định",
    executiveRole: "Ủy Viên BCH",
  },
  {
    id: "M1983-024",
    code: "M1983-024",
    name: "Nguyễn Thế Tư",
    contact: "Nguyễn Thế Tư",
    email: "vptdl.prudential.q10@gmail.com",
    phone: "0813946888",
    type: "company",
    level: "vip",
    industry: "đại lý và môi giới bảo hiểm",
    region: "region.north",
    status: "active",
    joinedAt: "2025-04-03T00:00:00Z",
    feeYear: 2026,
    feePaid: true,
    address: "71 Vĩnh Viễn, P2, Q10, Tp HCM",
    website: "https://ceo1983.vn",
    about: "Công ty bảo hiểm nhân thọ Prudential · Giám Đốc · đại lý và môi giới bảo hiểm",
    department: "Ban Truyền Thông & Sự Kiện",
    executiveRole: "Thành Viên",
  },
  {
    id: "M1983-025",
    code: "M1983-025",
    name: "Nguyễn Văn Thuy",
    contact: "Nguyễn Văn Thuy",
    email: "thuynv@minhdunggroup.vn",
    phone: "0913968388",
    type: "company",
    level: "vip",
    industry: "sản xuất máy giặt công nghệ, hoá chất",
    region: "region.north",
    status: "active",
    joinedAt: "2025-04-10T00:00:00Z",
    feeYear: 2026,
    feePaid: true,
    address: "số 15, ngách 93/29 Yên Sở, Hoàng Mai, Hà Nội",
    website: "https://ceo1983.vn",
    about: "Công ty CP Tập đoàn Minh Dũng · Chủ tịch HĐQT · sản xuất máy giặt công nghệ, hoá chất",
    department: "Ban Tài Chính & Pháp Chế",
    executiveRole: "Trưởng Ban",
  },
  {
    id: "M1983-026",
    code: "M1983-026",
    name: "Trần Đức Tuân",
    contact: "Trần Đức Tuân",
    email: "vpct@vtgroup.com.vn",
    phone: "0909588136",
    type: "company",
    level: "vip",
    industry: "đầu tư; hóa chất; nông sản; năng lượng; logitics",
    region: "region.north",
    status: "active",
    joinedAt: "2025-12-10T00:00:00Z",
    feeYear: 2026,
    feePaid: true,
    address: "117 Nguyễn Văn Hưởng, Khu phố 9, An Khánh, Tp Hồ Chí Minh",
    website: "https://ceo1983.vn",
    about: "Công ty CP Việt Thái Group · Chủ tịch HĐQT · đầu tư; hóa chất; nông sản; năng lượng; logitics",
    department: "Ban Đào Tạo & Chuyển Đổi Số",
    executiveRole: "Phó Ban",
  },
  {
    id: "M1983-027",
    code: "M1983-027",
    name: "Phạm Trung Thành",
    contact: "Phạm Trung Thành",
    email: "thanhphamphd@visionviet.vn",
    phone: "0911859969",
    type: "company",
    level: "vip",
    industry: "các sản phẩm số liên quan đến truyền thông và văn hóa",
    region: "region.north",
    status: "active",
    joinedAt: "2026-03-05T00:00:00Z",
    feeYear: 2026,
    feePaid: true,
    address: "tầng 15, tòa Technopark tower, KĐT Ocean Park 1, xã Gia Lâm, Hà Nội",
    website: "https://ceo1983.vn",
    about: "Công ty CP Vision Việt · Giám Đốc · các sản phẩm số liên quan đến truyền thông và văn hóa",
    department: "Ban Thư Ký & Điều Phối",
    executiveRole: "Ủy Viên BCH",
  }